id: resonancia-electrica
titulo: resonancia-electrica
type: leaf
orden: 294400
niveles:
  - UNIVERSIDAD
icon: 🌪️
ruta_relativa: fisica-clasica/electromagnetismo/corriente-alterna/resonancia-electrica
descripcion: 'Subtema: Resonancia Electrica. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
