// frontend/src/v2/components/SVG/profiles/sustentacion.svg.profile.jsx
//
// Profile SVG para: sustentacion (Nivel 5 v5)
//
import React from "react";
import {
  SVG_CONTROL_TYPES,
  SVG_MOTION_TYPES,
  SVG_SCENE_TYPES,
} from "../svgGrammar";
import { SvgArrow } from "../SvgProfileRenderer";

/* ── Helpers locales ─────────────────────────────────────────────────── */
const safeNum = (v, def = 0) => {
  if (typeof v === "number") return v;
  if (v && typeof v.value === "number") return v.value;
  const n = parseFloat(String(v ?? "").replace(",", "."));
  return Number.isFinite(n) ? n : def;
};

const fmt = (n, d = 1, lang = "es") => {
  if (!Number.isFinite(n)) return "-";
  const text = n.toFixed(d);
  return lang === "en" ? text : text.replace(".", ",");
};

const clamp = (n, a, b) => Math.max(a, Math.min(b, n));

/* ════════════════════════════════════════════════════════════════════════
 * PROFILE
 * ════════════════════════════════════════════════════════════════════════ */
const profile = {

  meta: {
    id: "svg-sustentacion",
    leafId: "sustentacion",
    title: {
      es: "Sustentación aerodinámica",
      en: "Aerodynamic lift",
    },
    subtitle: {
      es: "Diferencia de presión extradós / intradós → fuerza ascendente",
      en: "Pressure difference upper / lower surface → upward force",
    },
    graph_identity: {
      pregunta_principal: {
        es: "¿Cuál es la sustentación neta generada por el perfil?",
        en: "What is the net lift generated by the airfoil?",
      },
      magnitud_estrella: "dp",
    },
    interpretation_binding: {
      rho: "rho",
      v: "v",
      S: "S",
      C_L: "C_L",
      L: "L",
      dp: "dp",
    },
  },

  scene:     SVG_SCENE_TYPES.CUSTOM,
  viewBox:   "0 0 960 560",
  svgHeight: 640,

  /* ── Parámetros del simulador ─────────────────────────────────────── */
  params: {
    schema: [
      {
        key:     "rho",
        aliases: ["densidad", "density"],
        default: 1.225,
        label:   { es: "Densidad ρ (kg/m³)", en: "Density ρ (kg/m³)" },
        unit:    "kg/m³",
        type:    SVG_CONTROL_TYPES.RANGE,
        min:     0.1,
        max:     1.3,
        step:    0.025,
        decimals: 3,
      },
      {
        key:     "v",
        aliases: ["velocidad", "speed"],
        default: 60,
        label:   { es: "Velocidad v (m/s)", en: "Speed v (m/s)" },
        unit:    "m/s",
        type:    SVG_CONTROL_TYPES.RANGE,
        min:     0,
        max:     300,
        step:    5,
        decimals: 0,
      },
      {
        key:     "S",
        aliases: ["superficie", "area"],
        default: 14,
        label:   { es: "Superficie alar S (m²)", en: "Wing area S (m²)" },
        unit:    "m²",
        type:    SVG_CONTROL_TYPES.RANGE,
        min:     1,
        max:     600,
        step:    1,
        decimals: 0,
      },
      {
        key:     "C_L",
        aliases: ["cl", "coeficiente_sustentacion", "lift_coeff"],
        default: 1.2,
        label:   { es: "Coef. sustentación C_L", en: "Lift coeff. C_L" },
        type:    SVG_CONTROL_TYPES.RANGE,
        min:     0.1,
        max:     3.5,
        step:    0.05,
        decimals: 2,
      },
    ],
    derivations: {
      // L = 0.5 * rho * v^2 * S * C_L
      L: ({ rho, v, S, C_L }) =>
        0.5 * safeNum(rho, 1.225) * safeNum(v, 60) ** 2 * safeNum(S, 14) * safeNum(C_L, 1.2),
      // dp = 0.5 * rho * (v_sup^2 - v_inf^2) ≈ L / S
      dp: ({ rho, v, C_L }) =>
        0.5 * safeNum(rho, 1.225) * safeNum(v, 60) ** 2 * safeNum(C_L, 1.2),
    },
  },

  motion: {
    type: SVG_MOTION_TYPES.CUSTOM,
    state: (t, p) => {
      const v = safeNum(p?.v, 60);
      return { 
        flowOffset: -t * v * 2.5 
      };
    },
  },

  /* ── Tarjetas de información ─────────────────────────────────────── */
  infoCards: [
    {
      key: "lift",
      label: { es: "Fuerza de Sustentación", en: "Lift Force" },
      lines: ({ p, lang }) => {
        const rho  = safeNum(p?.rho,  1.225);
        const v    = safeNum(p?.v,    60);
        const S    = safeNum(p?.S,    14);
        const CL   = safeNum(p?.C_L,  1.2);
        const L    = 0.5 * rho * v * v * S * CL;
        const dp   = 0.5 * rho * v * v * CL;
        return [
          `L = ${fmt(L / 1000, 2, lang)} kN`,
          `Δp = ${fmt(dp, 0, lang)} Pa`,
        ];
      },
      result: ({ p, lang }) => {
        const L = 0.5 * safeNum(p?.rho,1.225) * safeNum(p?.v,60)**2 * safeNum(p?.S,14) * safeNum(p?.C_L,1.2);
        return `L = ${fmt(L/1000, 2, lang)} kN`;
      },
      resultColor: "#4ade80",
    },
    {
      key: "pressure",
      label: { es: "Diferencia de Presión", en: "Pressure Difference" },
      description: {
        es: "Presión neta ejercida por el fluido sobre el perfil.",
        en: "Net pressure exerted by the fluid on the airfoil.",
      },
      lines: ({ p, lang }) => {
        const rho  = safeNum(p?.rho, 1.225);
        const v    = safeNum(p?.v, 60);
        const CL   = safeNum(p?.C_L, 1.2);
        const dp   = 0.5 * rho * v * v * CL;
        return [`Δp = ${fmt(dp, 0, lang)} Pa` ];
      },
      result: ({ p, lang }) => {
        const dp = 0.5 * safeNum(p?.rho, 1.225) * safeNum(p?.v, 60)**2 * safeNum(p?.C_L, 1.2);
        return `${fmt(dp, 0, lang)} Pa`;
      },
      resultColor: "#fde68a",
    }
  ],

  /* ── Render SVG ───────────────────────────────────────────────────── */
  render: ({ p, state, lang = "es", toNum }) => {
    const isEs = lang !== "en";

    const rho  = clamp(toNum(p?.rho,  1.225), 0.1,  1.3);
    const v    = clamp(toNum(p?.v,    60),    0,    300);
    const S    = clamp(toNum(p?.S,    14),    1,    600);
    const CL   = clamp(toNum(p?.C_L,  1.2),  0.1,  3.5);

    const flowOffset = safeNum(state?.flowOffset, 0);

    const L  = 0.5 * rho * v * v * S * CL;
    const dp = 0.5 * rho * v * v * CL;

    // ── Normalización visual ───────────────────────────────────────
    const L_max  = 0.5 * 1.3 * 300 * 300 * 600 * 3.5;
    const L_norm = clamp(L / L_max, 0, 1);
    const arrowL = 20 + L_norm * 220;                     // 20 .. 240 px
    const arrowV = clamp(v / 300, 0, 1);
    const arrowVPx = 20 + arrowV * 160;

    // ── Geometría del perfil alar ──────────────────────────────────
    const WingCX = 480;
    const WingCY = 295;
    const CHORD  = 280;
    const THICK  = 52;

    const wingPathD = `
      M ${-CHORD/2} 0
      C ${-CHORD/2 + 40} ${-THICK} ${CHORD/2 - 80} ${-THICK * 0.7} ${CHORD/2} 0
      C ${CHORD/2 - 80} ${THICK * 0.2} ${-CHORD/2 + 40} ${THICK * 0.3} ${-CHORD/2} 0
      Z
    `;

    const flowLines = [
      { y: -100, gap: 1.0 },
      { y: -60, gap: 1.2 },
      { y: -35, gap: 1.5 },  // extradós — más separadas = más rápidas
      { y:  35, gap: 0.7 },  // intradós — más juntas = más lentas
      { y:  65, gap: 0.9 },
      { y:  100, gap: 1.0 },
    ];

    return (
      <g>
        <defs>
          <linearGradient id="sustBg" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%"   stopColor="#071520" />
            <stop offset="100%" stopColor="#0a1d2e" />
          </linearGradient>
          <linearGradient id="sustWing" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%"   stopColor="#60a5fa" stopOpacity="0.3" />
            <stop offset="100%" stopColor="#1d4ed8" stopOpacity="0.6" />
          </linearGradient>
        </defs>

        {/* ── Fondo ──────────────────────────────────────────────── */}
        <rect x="0" y="0" width="960" height="560" rx="20" fill="url(#sustBg)" />

        {/* ── Título ─────────────────────────────────────────────── */}
        <text x="480" y="44" textAnchor="middle" fill="#ffffff" fontSize="24" fontWeight="900" letterSpacing="0.5">
          {isEs ? "Sustentación Aerodinámica" : "Aerodynamic Lift"}
        </text>
        <text x="480" y="68" textAnchor="middle" fill="rgba(255,255,255,0.5)" fontSize="13" fontWeight="500">
          {isEs
            ? "Perfil alar: la asimetría del flujo genera una diferencia de presiones neta"
            : "Airfoil: flow asymmetry generates a net pressure difference"}
        </text>

        {/* ── Zona central ───────────────────────────────────────── */}
        <g transform={`translate(${WingCX}, ${WingCY})`}>

          {/* Líneas de flujo animadas */}
          {flowLines.map(({ y: yOff, gap }, i) => (
            <g key={i}>
              <line
                x1={-CHORD / 2 - 240}
                y1={yOff}
                x2={CHORD / 2 + 240}
                y2={yOff}
                stroke={gap > 1.2 ? "#93c5fd" : "#60a5fa"}
                strokeWidth={gap > 1.2 ? 2 : 1.5}
                strokeOpacity={0.25}
                strokeDasharray={`${12 * gap} ${8 / gap}`}
                strokeDashoffset={flowOffset * gap}
              />
            </g>
          ))}

          {/* Perfil alar */}
          <path d={wingPathD} fill="url(#sustWing)" stroke="none" />

          {/* Bordes */}
          <path d={wingPathD} fill="none" stroke="#93c5fd" strokeWidth="2.5" strokeOpacity="0.8" />

          {/* Etiquetas extradós / intradós */}
          <text x={-100} y={-THICK - 30} textAnchor="middle" fill="#93c5fd" fontSize="11" fontWeight="800" opacity="0.9">
            {isEs ? "EXTRADÓS (v↑, p↓)" : "UPPER SURFACE (v↑, p↓)"}
          </text>
          <text x={100} y={THICK + 40} textAnchor="middle" fill="#60a5fa" fontSize="11" fontWeight="800" opacity="0.8">
            {isEs ? "INTRADÓS (v↓, p↑)" : "LOWER SURFACE (v↓, p↑)"}
          </text>

          {/* ── Vector velocidad de flujo libre ────────────────── */}
          <SvgArrow
            x1={-CHORD / 2 - 160}
            y1={120}
            x2={-CHORD / 2 - 160 + arrowVPx}
            y2={120}
            color="#fbbf24"
            label={`v = ${fmt(v, 0, lang)} m/s`}
            strokeWidth={3}
          />

          {/* ── Vector sustentación L ──────────────────────────── */}
          <SvgArrow
            x1={0}
            y1={-THICK}
            x2={0}
            y2={-THICK - arrowL}
            color="#4ade80"
            label={`L = ${fmt(L / 1000, 2, lang)} kN`}
            labelDy={arrowL > 180 ? 25 : -10} // Evitar desborde superior
            strokeWidth={5}
          />

          {/* ── Δp label ───────────────────────────────────────── */}
          <g transform="translate(120, 0)">
            <text x={0} y={-4} fill="#fde68a" fontSize="12" fontWeight="900" textAnchor="middle">
              Δp = {fmt(dp, 0, lang)} Pa
            </text>
            <line x1={0} y1={-THICK + 5} x2={0} y2={THICK * 0.2 + 5}
              stroke="#fde68a" strokeWidth="1.5" strokeDasharray="4 3" opacity="0.6" />
            <line x1={-15} y1={-THICK + 5} x2={15} y2={-THICK + 5}
              stroke="#fde68a" strokeWidth="1.5" />
            <line x1={-15} y1={THICK * 0.2 + 5} x2={15} y2={THICK * 0.2 + 5}
              stroke="#fde68a" strokeWidth="1.5" />
          </g>

        </g>

        {/* ── Panel de resultados ────────────────────────────────── */}
        <rect x="30" y="380" width="230" height="150" rx="16"
          fill="rgba(15,23,42,0.7)" stroke="rgba(255,255,255,0.1)" />
        <text x="50" y="408" fill="#ffffff" fontSize="14" fontWeight="900" letterSpacing="1">
          {isEs ? "PARÁMETROS" : "PARAMETERS"}
        </text>
        <g fontSize="12" fill="rgba(255,255,255,0.7)" fontWeight="600">
          <text x="50" y="432">ρ = {fmt(rho, 3, lang)} kg/m³</text>
          <text x="50" y="452">v = {fmt(v, 0, lang)} m/s</text>
          <text x="50" y="472">S = {fmt(S, 0, lang)} m²</text>
          <text x="50" y="492">C_L = {fmt(CL, 2, lang)}</text>
        </g>
        <text x="50" y="518" fill="#4ade80" fontSize="15" fontWeight="900">
          L = {fmt(L / 1000, 2, lang)} kN
        </text>

        {/* ── Leyenda ────────────────────────────────────────────── */}
        <g transform="translate(300, 520)" fontSize="11" fontWeight="700">
           <rect x="0" y="0" width="10" height="10" fill="#fbbf24" rx="2" />
           <text x="15" y="9" fill="rgba(255,255,255,0.6)">{isEs ? "Velocidad" : "Velocity"}</text>
           
           <rect x="100" y="0" width="10" height="10" fill="#4ade80" rx="2" />
           <text x="115" y="9" fill="rgba(255,255,255,0.6)">{isEs ? "Sustentación" : "Lift"}</text>
           
           <rect x="210" y="0" width="10" height="10" fill="#fde68a" rx="2" />
           <text x="225" y="9" fill="rgba(255,255,255,0.6)">{isEs ? "Diferencia de presión" : "Pressure diff."}</text>

           <line x1="340" y1="5" x2="365" y2="5" stroke="#93c5fd" strokeWidth="2" strokeDasharray="5 3" />
           <text x="372" y="9" fill="rgba(255,255,255,0.6)">{isEs ? "Líneas de flujo" : "Streamlines"}</text>
        </g>

        {/* ── Nota física ────────────────────────────────────────── */}
        <text x="480" y="545" textAnchor="middle" fill="rgba(255,255,255,0.6)" fontSize="12" fontWeight="700">
          {isEs
            ? "L ∝ v²: duplicar la velocidad cuadruplica la sustentación."
            : "L ∝ v²: doubling speed quadruples lift."}
        </text>

        {/* ── Watermark ──────────────────────────────────────────── */}
        <text x="940" y="540" textAnchor="end" fontSize="10" fill="#ffffff" opacity="0.1"
          fontWeight="900" letterSpacing="2">
          PHYXIO V5 · AERODYNAMICS
        </text>
      </g>
    );
  },

  /* ── Interpretación textual (consumida por el panel lateral) ─────── */
  aside: {
    interpretation: {
      header_bridge: {
        es: "La sustentación no es magia: es una diferencia de presiones construida por la forma del ala.",
        en: "Lift is not magic: it is a pressure difference built by the wing shape.",
      },
      reading_focus: {
        es: "Observa cómo las líneas de flujo se separan más sobre el extradós (mayor velocidad) que bajo el intradós. Cada par de líneas anchas representa flujo acelerado → presión reducida.",
        en: "Notice how streamlines spread more over the upper surface (higher speed) than below the lower surface. Each wide pair of lines represents accelerated flow → reduced pressure.",
      },
      graph_role: {
        es: "Visualizar la asimetría de velocidades entre extradós e intradós, la diferencia de presión Δp resultante y la fuerza de sustentación L que actúa hacia arriba sobre el ala.",
        en: "Visualize the velocity asymmetry between upper and lower surfaces, the resulting pressure difference Δp, and the lift force L acting upward on the wing.",
      },
      physical_insight: {
        es: "La clave es que el extradós curvado obliga al fluido a acelerar. Por Bernoulli: mayor v → menor p. La diferencia de presiones integrada sobre toda la superficie alar (dp × S) produce la fuerza de sustentación. El coeficiente C_L condensa toda la geometría del perfil y el ángulo de ataque en un único número adimensional.",
        en: "The key is that the curved upper surface forces the fluid to accelerate. By Bernoulli: higher v → lower p. The pressure difference integrated over the whole wing area (dp × S) produces the lift force. The coefficient C_L condenses the entire aerofoil geometry and angle of attack into a single dimensionless number.",
      },
      calc_reading: {
        es: "Con la fórmula L = ½ρv²SC_L: aumentar v el doble multiplica L por cuatro (dependencia cuadrática). Reducir a la mitad la densidad (mayor altitud) reduce L a la mitad si todo lo demás es constante.",
        en: "With L = ½ρv²SC_L: doubling v multiplies L by four (quadratic dependence). Halving density (higher altitude) halves L if everything else stays constant.",
      },
      graph_reading: {
        es: "La flecha verde L crece con v² y con S. El segmento Δp marca la diferencia de presión entre intradós y extradós en el punto central del perfil.",
        en: "The green arrow L grows with v² and with S. The Δp segment marks the pressure difference between lower and upper surfaces at the wing's midpoint.",
      },
      likely_errors: {
        es: [
          "Creer que el extradós genera sustentación porque el fluido 'corre más rápido para llegar al otro extremo al mismo tiempo' (igual transit time): esto no tiene fundamento; la aceleración viene dada por la curvatura, no por la igualdad de tiempos.",
          "Olvidar convertir km/h a m/s antes de sustituir en la fórmula: 1 km/h = 1/3.6 m/s.",
          "Tratar C_L como constante fija ignorando que cambia con el ángulo de ataque.",
          "Confundir dp (diferencia de presión por unidad de área) con L (fuerza total): L = dp × S.",
          "Ignorar que ρ decrece con la altitud: a 10 000 m, ρ ≈ 0.41 kg/m³, frente a 1.225 a nivel del mar.",
        ],
        en: [
          "Believing the upper surface generates lift because the fluid 'must travel faster to arrive simultaneously' (equal transit time): this has no physical basis; acceleration comes from curvature, not timing.",
          "Forgetting to convert km/h to m/s before substituting: 1 km/h = 1/3.6 m/s.",
          "Treating C_L as a fixed constant, ignoring that it changes with angle of attack.",
          "Confusing dp (pressure difference per unit area) with L (total force): L = dp × S.",
          "Ignoring that ρ decreases with altitude: at 10 000 m, ρ ≈ 0.41 kg/m³, vs 1.225 at sea level.",
        ],
      },
    },
  },

  /* ── Binding calculadora → interpretación ───────────────────────── */
  interpretation_binding: {
    rho: "rho",
    v: "v",
    S: "S",
    C_L: "C_L",
    L: "L",
    dp: "dp",
  },
};

export default profile;
