export const STRICT_SVG_CONTRACT_LEAF_IDS = new Set([
  "momento-lineal",
  "impulso",
  "sistemas-aislados",
  "definicion-centro-de-masas",
  "centro-de-masas-sistemas-discretos",
  "movimiento-del-centro-de-masas",
  "marco-del-centro-de-masas",
  "colisiones-elasticas",
  "colisiones-inelasticas",
  "colisiones-totalmente-inelasticas",
  "colision-con-pared",
  "colisiones-2d",
  "dispersion-angular-en-colisiones-2d",
  "marco-del-centro-de-masas-en-colisiones",
  "enunciado-y-condiciones-de-aplicacion",
  "sistemas-aislados-y-fuerzas-externas",
  "impulso-externo-y-ruptura-de-la-conservacion",
  "conservacion-momento-angular",
  "precesion",
  "balance-de-momento-con-flujo-de-masa",
  "ecuacion-del-cohete",
]);

export function createSvgProfileContract({
  leafId,
  graphId,
  purpose,
  level,
  expectedInputs = [],
  acceptedAliases = {},
  derivedMagnitudes = [],
  targetCandidates = [],
  calcSyncConsumes = ["target", "result", "known", "formulaTitle"],
  paramsIn = expectedInputs,
  stateOut = derivedMagnitudes,
  selectableMagnitudes = [...new Set([...(targetCandidates || []), ...(derivedMagnitudes || [])])],
  supportsFocusTarget = true,
  equations = [],
  hypotheses = [],
  validityDomain = [],
  visualSimplifications = [],
  hasInternalTime = false,
  hasPlayPause = false,
  timeSemantics = "none",
  alwaysVisible = [],
  levelGatedLayers = [],
}) {
  return {
    identity: {
      leaf_id: leafId,
      graph_type: "Svg",
      graph_id: graphId,
      proposito_didactico: purpose,
      nivel_educativo: level,
    },
    calculator_contract: {
      expected_inputs: expectedInputs,
      accepted_aliases: acceptedAliases,
      derived_magnitudes: derivedMagnitudes,
      target_candidates: targetCandidates,
      calc_sync: {
        source: "sharedParams.__calc",
        consumes: calcSyncConsumes,
        mode_policy: "follow-calc-until-user-edit",
      },
    },
    interpretation_contract: {
      interpretation_binding: {
        paramsIn,
        stateOut,
        target: targetCandidates[0] || null,
      },
      selectable_magnitudes: selectableMagnitudes,
      emitted_semantic_context: [
        "profileId",
        "leafId",
        "target",
        "value",
        "paramsIn",
        "stateOut",
      ],
      supports_focus_target: supportsFocusTarget,
    },
    experiment_mode: {
      manipulable_params: expectedInputs,
      ranges_defined_in: "profile.params.schema",
      presets: [],
      calculator_lock_policy: "unlock-on-user-edit",
      reset_strategy: "schema-defaults",
    },
    physical_model: {
      equations,
      hypotheses,
      validity_domain: validityDomain,
      visual_simplifications: visualSimplifications,
    },
    animation: {
      has_internal_time: hasInternalTime,
      has_play_pause: hasPlayPause,
      time_semantics: timeSemantics,
    },
    visual_outputs: {
      always_visible: alwaysVisible,
      readable_magnitudes: selectableMagnitudes,
      level_gated_layers: levelGatedLayers,
    },
  };
}
