import React from 'react';
import { 
  SVG_CONTROL_TYPES, 
  SVG_MOTION_TYPES, 
  SVG_SCENE_TYPES,
  SVG_COLORS
} from "../svgGrammar";

const profile = {
  id: 'viscosidad',
  key: 'viscosidad',
  meta: {
    id: 'viscosidad',
    leafId: 'viscosidad',
    title: {
      es: 'Perfil de Viscosidad',
      en: 'Viscosity Profile'
    },
    subtitle: {
      es: 'Comportamiento de fluidos entre placas paralelas (Flujo de Couette).',
      en: 'Fluid behavior between parallel plates (Couette flow).'
    }
  },

  graph_identity: {
    pregunta_principal: {
      es: "¿Cómo cambia de forma un fluido bajo un esfuerzo cortante y de qué manera la viscosidad dinámica mide esa resistencia?",
      en: "How does a fluid change shape under shear stress and in what way does dynamic viscosity measure that resistance?",
    },
    magnitud_estrella: "tau",
  },

  interpretation_binding: {
    magnitudes: ["mu", "tau", "dudy"],
    formulas: ["tau_mu"],
    coordinate_system: "Cartesian (y, u)",
  },

  scene: SVG_SCENE_TYPES.CUSTOM,
  viewBox: "0 0 800 500",
  svgHeight: 520,

  params: {
    schema: [
      {
        key: 'mu',
        default: 0.001,
        label: { es: 'Viscosidad μ', en: 'Viscosity μ' },
        unit: 'Pa·s',
        type: SVG_CONTROL_TYPES.RANGE,
        min: 0.0001,
        max: 0.1,
        step: 0.0001
      },
      {
        key: 'V',
        default: 1,
        label: { es: 'Velocidad V', en: 'Velocity V' },
        unit: 'm/s',
        type: SVG_CONTROL_TYPES.RANGE,
        min: 0,
        max: 5,
        step: 0.1
      },
      {
        key: 'h',
        default: 0.02,
        label: { es: 'Separación h', en: 'Separation h' },
        unit: 'm',
        type: SVG_CONTROL_TYPES.RANGE,
        min: 0.005,
        max: 0.1,
        step: 0.005
      }
    ],
    derivations: {
      dudy: ({ V, h }) => Number(V) / Math.max(Number(h), 0.001),
      tau: ({ mu, V, h }) => Number(mu) * (Number(V) / Math.max(Number(h), 0.001))
    }
  },

  infoCards: [
    {
      key: 'tau_info',
      label: { es: 'Esfuerzo Cortante', en: 'Shear Stress' },
      result: ({ p, fmt }) => `τ = ${fmt(p.tau, 4)} Pa`,
      description: {
        es: 'Esfuerzo tangencial generado por la viscosidad.',
        en: 'Tangential stress generated by viscosity.'
      }
    },
    {
      key: 'mu_info',
      label: { es: 'Propiedad del Fluido', en: 'Fluid Property' },
      result: ({ p, fmt }) => `μ = ${fmt(p.mu, 4)} Pa·s`,
      description: {
        es: 'Viscosidad dinámica del fluido.',
        en: 'Dynamic viscosity of the fluid.'
      }
    }
  ],

  motion: { type: SVG_MOTION_TYPES.STATIC },

  render: ({ p, lang = "es", toNum, fmt }) => {
    const V = toNum(p.V, 1);
    const h = toNum(p.h, 0.02);
    const colors = SVG_COLORS;
    
    const xBase = 150;
    const yBase = 400;
    
    const hPx = h * 2000; // Visual scale
    const vPx = V * 60;

    return (
      <g>
        {/* Ground / Static Plate */}
        <rect x={xBase - 50} y={yBase} width="500" height="10" fill="#64748b" />
        
        {/* Moving Top Plate */}
        <rect x={xBase - 50} y={yBase - hPx - 10} width="500" height="10" fill={colors.VELOCITY} />
        
        {/* Fluid Body */}
        <rect x={xBase} y={yBase - hPx} width="400" height={hPx} fill={colors.VELOCITY} fillOpacity="0.1" />
        
        {/* Velocity Profile Polygon */}
        <polygon points={`${xBase},${yBase} ${xBase + vPx},${yBase - hPx} ${xBase},${yBase - hPx}`} fill={colors.VELOCITY} fillOpacity="0.2" />
        <line x1={xBase} y1={yBase} x2={xBase + vPx} y2={yBase - hPx} stroke={colors.VELOCITY} strokeWidth="2" strokeDasharray="5 5" />

        {/* Velocity Vectors */}
        {[0.25, 0.5, 0.75, 1.0].map(f => (
          <line 
            key={f}
            x1={xBase} 
            y1={yBase - f * hPx} 
            x2={xBase + f * vPx} 
            y2={yBase - f * hPx} 
            stroke={colors.ACCELERATION} 
            strokeWidth="2"
            markerEnd="url(#arrowhead-visc)"
          />
        ))}

        <text x={xBase + vPx + 10} y={yBase - hPx} fill="#fff" fontSize="16" fontWeight="950">V = {fmt(V, 1)} m/s</text>
        <text x={xBase - 80} y={yBase - hPx/2} fill="#94a3b8" fontSize="14" transform={`rotate(-90, ${xBase - 80}, ${yBase - hPx/2})`} textAnchor="middle">
          h = {fmt(h, 3)} m
        </text>

        <defs>
          <marker id="arrowhead-visc" markerWidth="10" markerHeight="7" refX="10" refY="3.5" orient="auto">
            <polygon points="0 0, 10 3.5, 0 7" fill={colors.ACCELERATION} />
          </marker>
        </defs>
      </g>
    );
  }
};

export default profile;
