version: 1
id: manometros
nombre: Manometros
titulo: manometros
type: leaf
area: fisica-clasica
bloque: mecanica
subbloque: fluidos
orden: 218251
niveles:
  - ESO
  - BACHILLERATO
  - UNIVERSIDAD
icon: 💧
ruta_relativa: fisica-clasica/mecanica/fluidos/estatica-de-fluidos/aplicaciones/manometros
descripcion: Medicion de presion con columnas de fluido.
descripcion_corta: Medicion de presion con columnas de fluido.
dificultad: 2
tiempo_estimado_min: 55
prerequisitos:
  - fisica-clasica/mecanica/fluidos/estatica-de-fluidos/presion-hidrostatica
tags:
  - fluidos
  - aplicaciones
  - manometros
graficos:
  - Coord
  - Svg
  - Dcl
