id: dosimetria-y-radioproteccion
titulo: dosimetria-y-radioproteccion
type: leaf
orden: 335000
niveles:
  - EXTRACURRICULAR
icon: 🌈
ruta_relativa: fisica-moderna/fisica-nuclear/dosimetria-y-radioproteccion
descripcion: 'Subtema: Dosimetria y Radioproteccion. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
