id: circuitos-rlc
titulo: circuitos-rlc
type: leaf
orden: 294300
niveles:
  - UNIVERSIDAD
icon: 🛰️
ruta_relativa: fisica-clasica/electromagnetismo/corriente-alterna/circuitos-rlc
descripcion: 'Subtema: Circuitos RLC. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
