id: biomasa
titulo: biomasa
type: leaf
orden: 571400
niveles:
  - EXTRACURRICULAR
icon: 🧯
ruta_relativa: sostenibilidad-energia/fuentes-de-energia/energias-renovables/biomasa
descripcion: 'Subtema: Biomasa. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
