id: ejemplos-practicos
titulo: ejemplos-practicos
type: leaf
orden: 258330
niveles:
  - BACHILLERATO
  - UNIVERSIDAD
  - EXTRACURRICULAR
icon: 📷
ruta_relativa: fisica-clasica/termodinamica/maquinas-termicas/refrigeradores-y-bombas-de-calor/ejemplos-practicos
descripcion: 'Subtema: Ejemplos Practicos. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
