id: respaldo-a-renovables
titulo: respaldo-a-renovables
type: leaf
orden: 594300
niveles:
  - EXTRACURRICULAR
icon: 🧴
ruta_relativa: sostenibilidad-energia/transporte-de-la-energia/ciclos-combinados-y-respaldo/respaldo-a-renovables
descripcion: 'Subtema: Respaldo a Renovables. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
