id: ley-de-ampere
titulo: ley-de-ampere
type: leaf
orden: 299320
niveles:
  - BACHILLERATO
  - UNIVERSIDAD
icon: 🪵
ruta_relativa: fisica-clasica/electromagnetismo/magnetismo/fuentes-del-campo-magnetico/ley-de-ampere
descripcion: 'Subtema: Ley de Ampere. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
