import { TheorySection, Concept, Formula    } from '../../../../components/TheoryV2';
import { definitions as propiedades_termicasDefinitions } from './definitions.js';

export const metadata = {
  titulo: "Propiedades Térmicas",
  descripcion: "Clasificación y características de las propiedades termodinámicas",
  educationLevel: 'BACHILLERATO',
  levels: ['BACHILLERATO'],
  isTheoryOnly: true
};

const PropiedadesTermicasTheory = ({ exercises }) => {
  return (
    <>
      <TheorySection title="Propiedades Intensivas y Extensivas">
        <Concept title="Clasificación Fundamental">
          <p>Propiedades intensivas temperatura presión densidad viscosidad índice refracción conductividad térmica resistividad eléctrica calor específico independientes cantidad materia sistema valor constante duplicar masa sistema temperatura no cambia 20°C permanece 20°C análisis local puntual medición sensores instrumentación control procesos.</p>
          
          <p>Características propiedades intensivas uniformidad espacial equilibrio térmico dos cuerpos diferentes masas misma temperatura contacto transferencia calor cesa igualdad propiedad intensiva temperatura termodinámica fundamento termometría calibración escalas absolutas Kelvin relativas Celsius Fahrenheit aplicación universal física química ingeniería biología ciencias ambientales meteorología.</p>
          
          <p>Propiedades extensivas masa m kilogramos volumen V metros cúbicos energía interna U julios entalpía H=U+PV entropía S joules/Kelvin cantidad movimiento p=mv proporcionales cantidad materia duplicar masa duplica volumen energía análisis global integral sistema completo aditividad subsistemas suma componentes principio conservación masa energía cantidad movimiento leyes fundamentales física.</p>
          
          <p>Diferencia conceptual intensivas punto material sistema homogéneo propiedad misma cada punto extensivas requieren integración todo volumen sistema acumulación materia energía dependencia tamaño escala sistema micro nano meso macro propiedades emergentes colectivas comportamiento estadístico promedio temporal espacial ensemble microcanónico canónico gran canónico mecánica estadística Boltzmann Gibbs conexión microscópico macroscópico.</p>
        </Concept>
      </TheorySection>

      <TheorySection title="Propiedades Específicas y Molares">
        <Concept title="Normalización por Masa y Moles">
          <p>Propiedad específica propiedad extensiva dividida masa sistema volumen específico v=V/m m³/kg inverso densidad ρ=m/V kg/m³ energía interna específica u=U/m kJ/kg entalpía específica h=H/m kJ/kg entropía específica s=S/m kJ/kg·K capacidad calorífica específica c_p=C_p/m kJ/kg·K propiedades intensivas útiles tablas vapor agua sustancias puras correlaciones empíricas ecuaciones estado.</p>
          
          <p>Propiedades molares normalización cantidad sustancia moles n=m/M masa molar M kg/mol volumen molar v̄=V/n m³/mol gases ideales 0°C 1atm 22.414L/mol número Avogadro N_A=6.022×10²³ partículas/mol constante universal gases R=8.314J/mol·K energía interna molar ū=U/n entalpía molar h̄=H/n entropía molar s̄=S/n capacidad calorífica molar c̄_p=C_p/n aplicación química estequiometría reacciones equilibrios termodinámicos constante equilibrio K_p K_c temperatura dependencia van't Hoff.</p>
          
          <p>Conversión específicas molares multiplicación división masa molar sustancia pura h=h̄/M s=s̄/M c_p=c̄_p/M relación directa proporcionalidad inversa masa molar mayor valores específicos menores molares mayores comparación sustancias diferentes agua M=18g/mol hidrógeno M=2g/mol helio M=4g/mol nitrógeno M=28g/mol oxígeno M=32g/mol dióxido carbono M=44g/mol propiedades normalizadas análisis comparativo estudio sistemático familias compuestos series homólogas alcanos alquenos alcohols ácidos carboxílicos.</p>
        </Concept>
      </TheorySection>

      <TheorySection title="Variables de Estado y Ecuaciones">
        <Concept title="Descripción Completa del Sistema">
          <p>Estado termodinámico sistema definido conjunto valores propiedades independientes variables estado presión P temperatura T volumen V masa m composición química x_i fracciones molares componentes sistema multicomponente descripción completa única determinación todas propiedades dependientes funciones estado energía interna U entalpía H entropía S energía libre Gibbs G energía libre Helmholtz F relaciones termodinámicas fundamentales.</p>
          
          <p>Regla fases Gibbs grados libertad F=C-P+2 componentes C fases equilibrio P variables independientes necesarias especificar estado sistema agua pura C=1 fase líquida P=1 libertad F=1-1+2=2 temperatura presión independientes punto triple tres fases equilibrio P=3 libertad F=1-3+2=0 temperatura presión fijas 0.01°C 611.657Pa invariante único mezcla binaria C=2 dos fases líquido vapor P=2 libertad F=2-2+2=2 temperatura composición independientes presión determinada.</p>
          
          <p>Ecuación estado fundamental relación matemática variables termodinámicas gases ideales PV=nRT constante universal R=8.314J/mol·K aproximación válida presiones bajas temperaturas altas gases reales desviaciones altas presiones bajas temperaturas ecuaciones van der Waals (P+a/v²)(v-b)=RT parámetros atracción repulsión Redlich-Kwong Soave Peng-Robinson correlaciones multiparámetro precisión industrial REFPROP simulación procesos químicos petroquímicos refrigeración criogenia.</p>
        </Concept>
      </TheorySection>

      <TheorySection title="Propiedades de Transporte">
        <Concept title="Transferencia de Cantidad de Movimiento, Energía y Masa">
          <p>Viscosidad dinámica μ Pa·s resistencia flujo deformación fluido tensión cortante proporcional gradiente velocidad ley Newton fluidos newtonianos agua aire aceites lubricantes viscosidad cinemática ν=μ/ρ m²/s difusividad momento lineal aplicación mecánica fluidos ecuaciones Navier-Stokes Reynolds número adimensional Re=ρvL/μ transición laminar turbulento Re_crítico=2300 tuberías 500000 placas planas aerodinámica hidrodinámica.</p>
          
          <p>Conductividad térmica λ W/m·K capacidad material conducir calor ley Fourier transferencia calórica flujo q proporcional gradiente temperatura q=-λ∇T metales alta conductividad λ_cobre=400W/m·K λ_aluminio=200W/m·K electrones libres movimiento térmico cerámicas aislantes baja λ_vidrio=1W/m·K λ_madera=0.15W/m·K λ_poliestireno=0.03W/m·K gases λ_aire=0.026W/m·K colisiones moleculares camino libre medio difusividad térmica α=λ/ρc_p m²/s rapidez difusión temperatura número Prandtl Pr=ν/α fluidos gases Pr≈1 aceites Pr≫1 metales líquidos Pr≪1.</p>
          
          <p>Difusividad másica D m²/s coeficiente difusión transporte materia ley Fick flujo molar J proporcional gradiente concentración J=-D∇c mezclas gases líquidos sólidos coeficiente interdifusión binario D_AB sustancia A en medio B valores típicos gases 10⁻⁵m²/s líquidos 10⁻⁹m²/s sólidos 10⁻¹⁴m²/s dependencia temperatura presión ecuación Arrhenius D=D₀exp(-E_a/RT) energía activación difusión aplicación procesos separación destilación absorción extracción membranas permeación catálisis heterogénea reacciones difusionales.</p>
        </Concept>
      </TheorySection>

      <TheorySection title="Tablas y Diagramas Termodinámicos">
        <Concept title="Representaciones Gráficas y Tabulares">
          <p>Tablas vapor agua sustancia trabajo más estudiada termodinámica aplicación industrial energética refrigeración climatización procesos químicos tabla saturación líquido-vapor temperatura presión saturación P_sat(T) relación unívoca Clausius-Clapeyron propiedades líquido saturado v_f h_f s_f vapor saturado v_g h_g s_g diferencias calor latente h_fg=h_g-h_f entropía vaporización s_fg=s_g-s_f tabla sobrecalentado vapor temperatura presión superiores saturación propiedades función independiente T,P interpolación lineal extrapolación precaución región supercrítica T {'>'} 374°C P {'>'} 221bar distinción líquido-vapor desaparece fluido supercrítico propiedades intermedias.</p>
          
          <p>Diagrama temperatura-entropía T-s Mollier representación procesos termodinámicos isentrópicos verticales isotermos horizontales isobáricos curvados izquierda isocóricos curvados derecha campana saturación líquido-vapor región bifásica título calidad x=(h-h_f)/(h_g-h_f) fracción vapor mezcla aplicación análisis ciclos potencia Rankine refrigeración compresión turbina expansión válvula ciclos combinados cogeneración.</p>
          
          <p>Diagrama presión-entalpía P-h log-log refrigeración fluidos frigorígenos R134a R410A R32 CO₂ amoniaco proceso evaporación isobárico horizontal baja presión compresión adiabático diagonal derecha condensación isobárico horizontal alta presión expansión isoentálpico vertical válvula termostática trabajo compresión área ciclo COP coeficiente prestación Q_evap/W_comp refrigerador bomba calor aplicación diseño selección equipos cálculo cargas térmicas optimización eficiencia energética.</p>
          
          <p>Diagrama fase P-T sólido-líquido-vapor líneas equilibrio bifásico sublimación fusión vaporización punto triple coexistencia tres fases punto crítico T_c P_c límite superior región bifásica líquido-vapor región supercrítica aplicación CO₂ supercrítico extracción cafeína descafeinado agua supercrítica oxidación residuos peligrosos hidrólisis biomasa conversión energética sostenible.</p>
        </Concept>
      </TheorySection>

      <div className="theory-applications-section">
        <h2><span>🌍</span> Aplicaciones en la vida real</h2>
        <div className="theory-subsection">
          <h3>Tabla vapor agua saturado propiedades temperatura presión</h3>
          <p>Las tablas de vapor son herramientas fundamentales en ingeniería térmica que recopilan propiedades termodinámicas del agua y vapor obtenidas experimentalmente. Un ingeniero diseñando una caldera que opera a 200°C necesita conocer todas las propiedades del vapor saturado a esa temperatura. Consultando la tabla de vapor saturado, encuentra que a 200°C la presión de saturación es exactamente 15.54 bar, y puede leer directamente múltiples propiedades: el volumen específico del líquido es 0.001157 m³/kg (casi incompresible) mientras que el vapor ocupa 0.1272 m³/kg (aproximadamente 110 veces más volumen).</p>
          <p>Las propiedades energéticas son igualmente importantes: la entalpía del líquido saturado es 852.4 kJ/kg, mientras que el vapor saturado tiene 2791 kJ/kg. La diferencia entre ambas (1938.6 kJ/kg) es el calor latente de vaporización, la enorme cantidad de energía requerida para cambiar de fase sin cambiar temperatura. Las entropías son 2.331 kJ/(kg·K) para el líquido y 6.428 kJ/(kg·K) para el vapor, reflejando el mayor desorden molecular del estado gaseoso.</p>
          <p>Estas propiedades tabuladas provienen de miles de mediciones experimentales precisas realizadas durante más de un siglo, complementadas con ecuaciones de estado y correlaciones empíricas validadas. Son esenciales para diseñar y analizar ciclos Rankine en centrales térmicas, calcular intercambiadores de calor, dimensionar tuberías de vapor y optimizar sistemas de calefacción industrial. Sin estas tablas, la ingeniería térmica moderna sería impracticable.</p>
        </div>
        <div className="theory-subsection">
          <h3>Densidad aceite motor viscosidad temperatura dependencia</h3>
          <p>El aceite de motor sintético, como un SAE 5W-30 típico, tiene una densidad de aproximadamente 850 kg/m³ a 15°C (temperatura de referencia estándar). Sin embargo, cuando el motor alcanza su temperatura de operación normal de 90°C, la densidad disminuye hasta unos 820 kg/m³ debido a la expansión térmica. Es crucial entender que la densidad es una propiedad intensiva: no importa si el cárter contiene 4 litros o 5 litros de aceite, la densidad en ambos casos será la misma a una temperatura dada. Esta característica permite comparar y especificar aceites independientemente de la cantidad presente.</p>
          <p>La viscosidad, otra propiedad intensiva del aceite, exhibe una dependencia aún más dramática con la temperatura. A 40°C, la viscosidad cinemática típica es de 60 cSt (centistokes), pero al calentar hasta 100°C se reduce drásticamente a apenas 10 cSt, una sexta parte del valor inicial. Esta reducción de viscosidad con la temperatura es esencial para el funcionamiento del motor: en arranque frío, el aceite debe ser suficientemente fluido para circular rápidamente y lubricar componentes; en operación caliente, debe mantener viscosidad suficiente para formar películas lubricantes efectivas.</p>
          <p>La correcta lubricación de cojinetes, pistones y otras partes móviles depende críticamente de estas propiedades. Un aceite con el grado SAE adecuado minimiza la fricción y el desgaste en todo el rango de temperaturas operativas, mejorando la eficiencia mecánica del motor (menos energía perdida en fricción) y reduciendo el consumo de combustible. Los aceites sintéticos modernos están formulados con aditivos especiales para mantener propiedades óptimas incluso en condiciones extremas de temperatura y presión.</p>
        </div>
        <div className="theory-subsection">
          <h3>Capacidad calorífica agua climatización acumulación térmica</h3>
          <p>El agua tiene una capacidad calorífica específica excepcionalmente alta de 4.18 kJ/(kg·K), la más elevada de casi todas las sustancias comunes. Esta propiedad la convierte en el medio ideal para almacenamiento térmico. Consideremos un depósito de acumulación térmica de 1000 litros (equivalente a 1000 kg de agua), calentado desde una temperatura inicial de 60°C hasta una final de 80°C, un incremento de 20 K. La energía térmica almacenada se calcula mediante Q = m·c_p·ΔT = 1000 kg × 4.18 kJ/(kg·K) × 20 K = 83,600 kJ = 23.2 kWh.</p>
          <p>Este ejemplo ilustra la distinción entre propiedades extensivas e intensivas. La energía total almacenada (83,600 kJ) es una propiedad extensiva que depende de la cantidad de agua: si duplicamos el volumen a 2000 litros, la energía almacenada se duplica a 46.4 kWh. En contraste, la capacidad calorífica específica (4.18 kJ/(kg·K)) es una propiedad intensiva que permanece constante, independientemente de si tenemos 1 litro o 1000 litros de agua. Esta distinción es fundamental para escalar sistemas correctamente.</p>
          <p>Esta alta capacidad de almacenamiento energético hace al agua indispensable en sistemas de energía solar térmica, donde los colectores calientan el agua durante el día para uso nocturno; en calefacción por suelo radiante, donde acumuladores térmicos estabilizan la temperatura; y en sistemas de agua caliente sanitaria (ACS) que proveen demanda variable con generación constante. El ahorro energético es considerable: estos sistemas reducen picos de demanda eléctrica y aprovechan tarifas nocturnas más económicas, con retornos de inversión típicos de 5-10 años.</p>
        </div>
        <div className="theory-subsection">
          <h3>Presión neumático temperatura volumen ley gases ideales</h3>
          <p>Un neumático de automóvil típico tiene un volumen interno de aproximadamente 30 litros y se infla a una presión recomendada de 2.2 bar (presión absoluta: 3.2 bar incluyendo la presión atmosférica) a temperatura ambiente de 20°C (293 K). Durante la conducción prolongada, especialmente en autopista o en verano, la fricción con el asfalto genera calentamiento significativo que puede elevar la temperatura del neumático hasta 60°C (333 K). Como el neumático es esencialmente rígido (volumen prácticamente constante), este aumento de temperatura provoca un incremento de presión según la ley de Gay-Lussac para procesos isocóricos.</p>
          <p>Aplicando la relación P₁/T₁ = P₂/T₂, donde P₁ = 2.2 bar y T₁ = 293 K son las condiciones iniciales, podemos calcular la presión final: P₂ = P₁ × (T₂/T₁) = 2.2 bar × (333 K / 293 K) = 2.5 bar, un aumento de 0.3 bar o aproximadamente 14%. Este efecto explica por qué los neumáticos deben revisarse en frío: medir la presión inmediatamente después de conducir daría lecturas artificialmente elevadas que podrían llevar a subinflar los neumáticos, comprometiendo seguridad y eficiencia.</p>
          <p>La presión es una propiedad intensiva: todos los puntos dentro del neumático tienen la misma presión, independientemente de la cantidad total de aire o del tamaño del neumático. Por eso los cuatro neumáticos de un vehículo deben inflarse a la misma presión especificada (típicamente diferente entre ejes delantero y trasero), garantizando comportamiento uniforme, contacto óptimo con el pavimento, desgaste parejo, eficiencia de combustible y seguridad en frenado y maniobras. Un inflado incorrecto (±0.3 bar) puede aumentar el consumo de combustible un 3-5% y reducir drásticamente la vida útil del neumático.</p>
        </div>
        <div className="theory-subsection">
          <h3>Entalpía combustión gasolina energía específica propulsión</h3>
          <p>La gasolina tiene un poder calorífico inferior (LHV, Lower Heating Value) de aproximadamente 44 MJ/kg, que representa la entalpía de combustión específica por unidad de masa. Esta es una propiedad intensiva fundamental: no importa si quemamos 1 kg o 50 kg de gasolina, el valor energético por kilogramo permanece constante en 44 MJ/kg. Esta propiedad intensiva permite calcular fácilmente la energía total disponible multiplicando por la masa de combustible, independientemente de la cantidad utilizada.</p>
          <p>Consideremos un vehículo con consumo típico de 8 L/100 km en carretera. Con una densidad de gasolina de 750 kg/m³, esos 8 litros equivalen a 6 kg de combustible por cada 100 km recorridos. La energía química total contenida es 6 kg × 44 MJ/kg = 264 MJ. Si el vehículo viaja a velocidad constante de 100 km/h durante 1 hora (3600 s) y desarrolla una potencia mecánica media de 50 kW en las ruedas, la energía mecánica útil entregada es 50 kW × 3.6 MJ/kWh = 180 MJ.</p>
          <p>La eficiencia global del motor Otto resulta ser 180 MJ / 264 MJ = 68%, lo cual puede parecer sorprendentemente alto pero es engañoso: esta cifra representa solo la eficiencia del motor en condiciones óptimas de carretera. En realidad, solo alrededor del 25-30% de la energía química se convierte en trabajo mecánico útil en el cigüeñal; el resto se pierde como calor en los gases de escape (35%), refrigeración del motor (30%), fricción mecánica (5-10%) y otras pérdidas. La potencia de 50 kW medida incluye pérdidas en transmisión, resistencia aerodinámica y rodadura, por lo que la eficiencia neta del sistema completo vehículo es típicamente solo del 12-20% en condiciones urbanas y 20-25% en autopista.</p>
        </div>
      </div>

      <div className="theory-history-section">
        <h2><span>📜</span> Historia y Desarrollo</h2>
        <div className="theory-subsection">
          <h3>Siglo XVIII desarrollo termometría temperatura propiedad intensiva</h3>
          <p>Daniel Gabriel Fahrenheit (1686-1736), fabricante de instrumentos científicos en Ámsterdam, inventó el termómetro de mercurio en 1714, revolucionando la medición de temperatura. Su escala Fahrenheit establecía 32°F como el punto de fusión del hielo y 212°F como el punto de ebullición del agua a presión atmosférica normal, dividiendo este intervalo en 180 divisiones iguales. El mercurio resultó ideal por su expansión térmica uniforme, amplio rango de temperaturas en estado líquido (-39°C a +357°C) y excelente visibilidad. La precisión, reproducibilidad y facilidad de calibración de estos termómetros los convirtieron en el estándar científico e industrial durante dos siglos.</p>
          <p>Anders Celsius (1701-1744), astrónomo sueco, propuso en 1742 una escala alternativa más intuitiva y compatible con el sistema decimal emergente. Originalmente estableció 0°C como el punto de ebullición del agua y 100°C como el de fusión del hielo, pero esta escala "invertida" fue corregida después de su muerte a la convención actual: 0°C para fusión y 100°C para ebullición. La escala Celsius ganó aceptación universal en ciencia gracias a su simplicidad decimal y su integración natural con el sistema métrico, convirtiéndose en el estándar internacional (SI) para temperatura cotidiana.</p>
          <p>Estos desarrollos establecieron la temperatura como una propiedad intensiva fundamental: dos cuerpos de tamaños muy diferentes en contacto térmico alcanzan la misma temperatura de equilibrio, independientemente de sus masas o volúmenes. Este concepto de propiedad intensiva, que no depende de la cantidad de materia, fue crucial para el desarrollo de la termodinámica y permitió la medición, control y optimización de procesos industriales, químicos y biológicos que caracterizarían la Revolución Industrial.</p>
        </div>
        <div className="theory-subsection">
          <h3>Siglo XIX tablas vapor Regnault propiedades saturación</h3>
          <p>Henri Victor Regnault (1810-1878), químico y físico francés, realizó durante las décadas de 1840-1860 las mediciones más precisas y sistemáticas de propiedades del vapor de agua jamás realizadas hasta entonces. Sus tablas de vapor saturado documentaban con exactitud sin precedentes cómo varían la presión de saturación, volumen específico, entalpía y calor latente de vaporización en función de la temperatura. Crucialmente, Regnault demostró experimentalmente las desviaciones significativas del comportamiento de gas ideal que presenta el vapor de agua a altas presiones, refutando simplificaciones teóricas previas y estableciendo la necesidad de datos empíricos precisos.</p>
          <p>Su trabajo experimental en el laboratorio de la École Polytechnique de París empleó aparatos sofisticados de calorimetría (medición de calor), manometría (medición de presión) y termometría (medición de temperatura) diseñados específicamente para máxima precisión. Implementó protocolos rigurosos de calibración y verificó la reproducibilidad de sus resultados mediante múltiples mediciones independientes. La publicación de sus tablas en 1847 fue un hito: de inmediato se convirtieron en referencia universal para ingenieros diseñando máquinas de vapor, calderas y las primeras turbinas de vapor.</p>
          <p>Las tablas de Regnault fueron fundamentales para la Revolución Industrial, permitiendo el diseño cuantitativo y optimizado de sistemas de potencia basados en vapor. Además, proporcionaron la validación experimental necesaria para las teorías termodinámicas emergentes de Carnot, Clausius y Rankine. Por primera vez, los ingenieros podían calcular con precisión eficiencias teóricas y compararlas con rendimientos reales, impulsando mejoras sistemáticas en la tecnología de vapor que dominó el siglo XIX.</p>
        </div>
        <div className="theory-subsection">
          <h3>Inicio siglo XX Gibbs potenciales termodinámicos propiedades fundamentales</h3>
          <p>Josiah Willard Gibbs (1839-1903) desarrolló el marco matemático riguroso que unificó todas las propiedades termodinámicas mediante los potenciales termodinámicos. Identificó cuatro funciones fundamentales del estado: energía interna U, entalpía H = U + PV, energía libre de Helmholtz F = U - TS, y energía libre de Gibbs G = H - TS. Cada una de estas funciones es natural para diferentes conjuntos de variables independientes (volumen-temperatura, presión-temperatura, etc.), permitiendo elegir la formulación más conveniente según las condiciones experimentales o del problema.</p>
          <p>Gibbs derivó las famosas relaciones de Maxwell, identidades que conectan derivadas parciales de diferentes propiedades termodinámicas mediante simetrías matemáticas. Por ejemplo, (∂S/∂V)_T = (∂P/∂T)_V relaciona cómo la entropía cambia con el volumen a temperatura constante con cómo la presión cambia con la temperatura a volumen constante. Estas relaciones son extraordinariamente poderosas: permiten calcular propiedades difíciles de medir directamente (como cambios de entropía) a partir de cantidades fácilmente medibles (como presión, volumen y temperatura).</p>
          <p>El formalismo de Gibbs estableció que conociendo una ecuación de estado completa (relación entre P, V, T y energía interna), se puede derivar toda la información termodinámica del sistema, incluyendo todas las demás propiedades calculables mediante transformaciones matemáticas. Este marco teórico permite predicciones que luego se verifican experimentalmente. Hoy, la IAPWS (International Association for the Properties of Water and Steam) utiliza ecuaciones de estado basadas en energía libre de Helmholtz para generar las tablas de vapor estándar industriales y científicas, cerrando el círculo entre teoría y experimento iniciado por Gibbs hace más de un siglo.</p>
        </div>
        <div className="theory-subsection">
          <h3>Era computacional bases datos NIST REFPROP propiedades fluidos</h3>
          <p>El National Institute of Standards and Technology (NIST) de Estados Unidos ha desarrollado desde los años 1980 hasta la actualidad REFPROP (Reference Fluid Thermodynamic and Transport Properties), una base de datos computacional que representa el estándar oro internacional para propiedades de fluidos. REFPROP contiene datos para 147 fluidos puros y más de 200 mezclas predefinidas, cubriendo rangos extraordinariamente amplios de temperatura y presión. Utiliza algoritmos sofisticados basados en ecuaciones de estado de Helmholtz multiparámetro ajustadas a miles de puntos experimentales, alcanzando precisiones del 0.1-1% en propiedades PVT (presión-volumen-temperatura), calor específico, velocidad del sonido, viscosidad y conductividad térmica.</p>
          <p>Las aplicaciones de REFPROP son omnipresentes en ingeniería moderna: diseño de sistemas de refrigeración y aire acondicionado (selección de refrigerantes, cálculo de ciclos), criogenia (licuefacción de gases, almacenamiento de hidrógeno líquido), procesamiento de gas natural y petroquímica (separación de componentes, diseño de tuberías), e industria química general. Ingenieros utilizan REFPROP para diseñar intercambiadores de calor, dimensionar compresores y turbinas, y optimizar procesos completos mediante balances de masa y energía precisos.</p>
          <p>La integración de REFPROP como biblioteca en software comercial de simulación de procesos (Aspen Plus, HYSYS, ProII) ha revolucionado la ingeniería química: permite simular plantas completas con precisión termodinámica rigurosa, optimizar condiciones operativas, y explorar diseños alternativos virtualmente antes de construir prototipos físicos costosos. REFPROP se ha convertido en el estándar internacional de facto en investigación académica, desarrollo tecnológico y aplicaciones industriales, certificando que los cálculos termodinámicos en cualquier parte del mundo se basan en las mismas propiedades de referencia validadas experimentalmente.</p>
        </div>
      </div>

      <div className="theory-anecdotes-section">
        <h2><span>🎭</span> Curiosidades y Anécdotas</h2>
        <div className="theory-subsection">
          <h3>Volumen específico agua anomalía 4°C densidad máxima</h3>
          <p>La inmensa mayoría de las sustancias se comportan de manera predecible al enfriarse: se contraen monotónicamente, aumentando su densidad conforme disminuye la temperatura. El agua, sin embargo, presenta una anomalía extraordinaria que ha sido crucial para la evolución de la vida en la Tierra. El agua alcanza su densidad máxima de 999.97 kg/m³ (equivalentemente, su volumen específico mínimo de 1.00003×10⁻³ m³/kg) a 3.98°C, no a 0°C como cabría esperar. Esta anomalía se debe a la competencia entre dos efectos: la contracción térmica normal y la formación progresiva de una estructura cristalina incipiente mediante enlaces de hidrógeno que tiende a expandir el líquido.</p>
          <p>Al enfriarse desde 4°C hasta 0°C, el agua se expande contra la intuición, disminuyendo su densidad de 999.97 kg/m³ a 999.84 kg/m³. Al congelarse a 0°C, el hielo tiene una densidad aún menor de 917 kg/m³, aproximadamente 9% menos denso que el agua líquida, lo que explica por qué el hielo flota. Este comportamiento anómalo tiene consecuencias ecológicas profundas: en invierno, cuando un lago se enfría, el agua superficial más fría (menos densa) permanece en la superficie y congela allí primero, formando una capa de hielo flotante que actúa como aislante térmico.</p>
          <p>Bajo esta capa de hielo, el agua líquida más densa a 4°C permanece en el fondo, nunca congelando completamente excepto en climas árticos extremos. Esto permite que la vida acuática (peces, plantas, microorganismos) sobreviva durante el invierno en el agua líquida del fondo, preservando ecosistemas completos y biodiversidad. Si el agua se comportara "normalmente", los lagos se congelarían desde el fondo hacia arriba, matando toda la vida acuática cada invierno y alterando drásticamente la evolución de la vida en la Tierra. Esta peculiar propiedad intensiva del agua ha sido literalmente esencial para la vida tal como la conocemos.</p>
        </div>
        <div className="theory-subsection">
          <h3>Punto triple agua definición Kelvin temperatura termodinámica</h3>
          <p>El punto triple del agua es la única combinación de temperatura y presión donde las tres fases (sólido, líquido y vapor) coexisten simultáneamente en equilibrio termodinámico estable. Este punto ocurre a exactamente 273.16 K y 611.657 Pa (aproximadamente 0.01°C y 0.006 atm). Entre 1954 y 2019, este punto definió la escala Kelvin de temperatura termodinámica absoluta: por convención internacional, se asignó al punto triple del agua el valor de 273.16 K, y un kelvin se definió como 1/273.16 de esta temperatura. Esta definición proporcionaba un estándar reproducible universalmente.</p>
          <p>En 2019, el Sistema Internacional redefinió el kelvin fijando la constante de Boltzmann k_B a un valor numérico exacto (1.380649×10⁻²³ J/K), vinculando la temperatura directamente a la energía cinética molecular promedio a nivel fundamental. Sin embargo, el punto triple del agua sigue siendo crucial en metrología práctica: celdas de punto triple (ampollas de vidrio selladas conteniendo agua ultra-pura degasificada) se usan para calibración de termómetros primarios con reproducibilidad de ±0.0001 K, una precisión extraordinaria.</p>
          <p>Laboratorios nacionales de metrología (NIST en EE.UU., PTB en Alemania, NPL en Reino Unido) mantienen celdas de punto triple como estándares primarios, estableciendo la trazabilidad de todas las mediciones de temperatura a nivel mundial. Cada termómetro industrial, cada sensor de temperatura en hospitales, laboratorios e industrias, puede rastrear su calibración hasta estos estándares primarios mediante cadenas de calibración documentadas. Esta infraestructura metrológica global garantiza que una temperatura medida en Tokio, Nueva York o Sydney tiene el mismo significado físico, fundamental para el comercio internacional, investigación científica colaborativa y seguridad industrial.</p>
        </div>
        <div className="theory-subsection">
          <h3>Helio superfluido viscosidad cero propiedad cuántica macroscópica</h3>
          <p>Cuando el helio-4 se enfría por debajo de 2.17 K (conocida como temperatura lambda), sufre una transición de fase extraordinaria hacia el estado de superfluido He-II, exhibiendo viscosidad literalmente cero. Este superfluido fluye sin fricción alguna a través de tubos capilares microscopic os, escala paredes de recipientes desafiando la gravedad, y presenta el "efecto fuente" donde flujos espontáneos de helio superfluido generan surtidores. Estos fenómenos imposibles de explicar clásicamente son manifestaciones macroscópicas directas de la mecánica cuántica: el helio superfluido es un condensado de Bose-Einstein, donde miles de millones de átomos ocupan el mismo estado cuántico, comportando se como una única función de onda macroscópica coherente.</p>
          <p>Pyotr Kapitsa descubrió la superfluidez en 1938 mediante experimentos meticulosos, recibiendo el Premio Nobel de Física en 1978 por este trabajo. Su experimento clásico demostró que una película delgada de helio superfluido puede escalar las paredes de un recipiente, fluir sobre el borde y gotear espontáneamente hacia abajo, comportamiento absolutamente imposible para cualquier líquido clásico. La superfluidez representa uno de los ejemplos más espectaculares donde efectos cuánticos, normalmente confinados a escalas atómicas, se vuelven visibles a escala macroscópica cotidiana.</p>
          <p>Las aplicaciones prácticas son fundamentales en física experimental moderna: el helio superfluido se utiliza en criogenia para refrigerar magnetos superconductores a temperaturas ultracold. El Gran Colisionador de Hadrones (LHC) del CERN utiliza aproximadamente 120 toneladas de helio superfluido a 1.9 K para enfriar sus 1232 magnetos superconductores dipolares y 392 cuadrupolares, creando campos magnéticos de 8.3 tesla necesarios para curvar trayectorias de protones a 0.999999991c. Sin helio superfluido, la física de partículas de altas energías moderna sería imposible, demostrando cómo propiedades termodinámicas exóticas habilitan tecnologías frontera.</p>
        </div>
        <div className="theory-subsection">
          <h3>Diamante grafito carbono propiedades opuestas estructura cristalina</h3>
          <p>El carbono (Z=6, configuración electrónica 1s²2s²2p²) exhibe alotropía extraordinaria: el mismo elemento forma estructuras radicalmente diferentes (diamante, grafito, fullerenos, nanotubos, grafeno) con propiedades completamente opuestas. El diamante presenta una red cristalina cúbica con hibridación sp³, donde cada átomo de carbono forma cuatro enlaces sigma covalentes tetraédricos extremadamente fuertes con sus vecinos. Esta estructura tridimensional rígida confiere al diamante la dureza máxima en la escala de Mohs (10), una conductividad térmica extraordinaria de 2200 W/(m·K) (superior a los metales), pero aislamiento eléctrico completo (sin electrones libres). Ópticamente, el diamante es transparente a la luz visible con índice de refracción altísimo (2.42) que produce su brillo y dispersión característicos, convir tiéndolo en la gema preciosa por excelencia.</p>
          <p>El grafito, en contraste dramático, tiene estructura hexagonal laminar con hibridación sp²: cada átomo forma tres enlaces sigma en un plano, dejando un electrón deslo calizado en orbitales pi conjugados. Los planos hexagonales se apilan mediante débiles fuerzas de van der Waals, permitiendo fácil deslizamiento que convierte al grafito en excelente lubricante sólido. La conducción eléctrica es anisótropa: alta dentro de los planos (electrones pi deslocalizados) pero baja entre planos. Ópticamente, el grafito es negro opaco absorbiendo toda la luz visible, utilizándose en lápices ("grafito" proviene del griego "graphein", escribir) donde las capas se desprenden dejando marcas negras sobre papel.</p>
          <p>Este contraste extremo entre diamante y grafito constituye el ejemplo paradigmático en ciencia de materiales de cómo la disposición atómica, tipo de enlace químico y geometría molecular determinan completamente las propiedades macroscópicas observables. Mismo elemento, mismos átomos, pero ordenados diferentemente: resultado, propiedades intensivas (dureza, conductividad, transparencia) totalmente opuestas. Esta relación estructura-propiedad es el principio central de la ingeniería de materiales moderna, permitiendo diseñar materiales con propiedades específicas manipulando estructura atómica mediante síntesis, tratamientos térmicos o dopaje.</p>
        </div>
      </div>

      <div className="theory-summary-section">
        <h2><span>📝</span> Resumen</h2>
        <ul>
          <li>
            Propiedades intensivas - independientes de la cantidad: Las propiedades intensivas como temperatura, presión y densidad tienen valores constantes en cada punto del sistema, independientemente de cuánta materia esté presente. Esta característica las hace ideales para análisis local o puntual: un sensor de temperatura mide la misma temperatura sin importar el tamaño del objeto. Dos cuerpos de masas muy diferentes en equilibrio térmico tienen la misma temperatura, demostrando que las propiedades intensivas reflejan el estado local, no la extensión del sistema.
          </li>
          <li>
            Propiedades extensivas - proporcionales a la cantidad: Masa, volumen, energía interna, entalpía y entropía son propiedades extensivas que escalan directamente con la cantidad de materia. Si duplicamos la masa del sistema, duplicamos su volumen, energía, entalpía y entropía. Esta aditividad permite sumar contribuciones de subsistemas para análisis global: la masa total de un sistema compuesto es la suma de las masas de sus partes. Las propiedades extensivas son fundamentales para balances integrales de masa y energía en ingeniería de procesos.
          </li>
          <li>
            Propiedades específicas - normalización por unidad de masa: Al dividir cualquier propiedad extensiva por la masa, obtenemos su correspondiente propiedad específica intensiva: volumen específico v = V/m (m³/kg), entalpía específica h = H/m (kJ/kg), entropía específica s = S/m (kJ/(kg·K)). Esta normalización es extremadamente útil porque convierte propiedades extensivas en intensivas, permitiendo comparar sistemas de diferentes tamaños y tabular propiedades de sustancias independientemente de la cantidad considerada. Las tablas de vapor utilizan exclusivamente propiedades específicas por esta razón.
          </li>
          <li>
            Tablas de vapor - datos experimentales tabulados: Las tablas de vapor del agua (saturado, sobrecalentado, comprimido) recopilan propiedades termodinámicas medidas experimentalmente con alta precisión en función de temperatura y presión. Estas tablas son indispensables para diseñar y analizar ciclos Rankine en centrales térmicas, calcular intercambiadores de calor, dimensionar turbinas de vapor y optimizar sistemas de potencia. Representan más de 150 años de mediciones experimentales meticulosas iniciadas por Regnault en el siglo XIX y continuadas por IAPWS hasta hoy.
          </li>
          <li>
            Ecuaciones de estado - relaciones PVT analíticas: Mientras que las tablas proveen datos discretos, las ecuaciones de estado proporcionan relaciones matemáticas continuas entre presión, volumen y temperatura: gases ideales (PV = nRT), van der Waals (correcciones por volumen molecular y fuerzas intermoleculares), Redlich-Kwong, Peng-Robinson (mayor precisión para gases reales y líquidos). Estas ecuaciones permiten predicción y extrapolación de propiedades termodinámicas, simulación computacional de procesos, y diseño de equipos sin necesidad de mediciones experimentales en cada condición posible.
          </li>
          <li>
            Bases de datos computacionales - NIST REFPROP estándar internacional: NIST REFPROP es la base de datos computacional de referencia mundial para propiedades termodinámicas y de transporte, conteniendo datos para 147 fluidos puros y 200+ mezclas. Utilizando ecuaciones de estado de Helmholtz multiparámetro ajustadas a miles de puntos experimentales, alcanza precisiones del 0.1-1%. Su integración en software de ingeniería (Aspen Plus, HYSYS, ProII) permite simulación rigurosa de procesos químicos, diseño optimizado de equipos, y cálculos termodinámicos trazables al estándar internacional en investigación, desarrollo y aplicaciones industriales globales.
          </li>
        </ul>
      </div>
    </>
  );
};

export default PropiedadesTermicasTheory;