id: campo-magnetico
titulo: campo-magnetico
type: leaf
orden: 299100
niveles:
  - BACHILLERATO
icon: 🏞️
ruta_relativa: fisica-clasica/electromagnetismo/magnetismo/campo-magnetico
descripcion: 'Subtema: Campo Magnetico. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
