id: generacion-transporte-distribucion
titulo: generacion-transporte-distribucion
type: leaf
orden: 592100
niveles:
  - EXTRACURRICULAR
icon: 🟪
ruta_relativa: sostenibilidad-energia/transporte-de-la-energia/red-electrica/generacion-transporte-distribucion
descripcion: 'Subtema: Generacion Transporte Distribucion. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
