id: confinamiento
titulo: confinamiento
type: leaf
orden: 424000
niveles:
  - EXTRACURRICULAR
icon: ⚛️
ruta_relativa: fisica-avanzada/fisica-plasmas/confinamiento
descripcion: 'Subtema: Confinamiento. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
