id: pozo-potencial
titulo: pozo-potencial
type: leaf
orden: 325000
niveles:
  - UNIVERSIDAD
icon: 🪞
ruta_relativa: fisica-moderna/mecanica-cuantica/pozo-potencial
descripcion: 'Subtema: Pozo Potencial. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
