version: 1
id: tubo-de-pitot
nombre: Tubo De Pitot
titulo: tubo-de-pitot
type: leaf
area: fisica-clasica
bloque: mecanica
subbloque: fluidos
orden: 218332
niveles:
  - ESO
  - BACHILLERATO
  - UNIVERSIDAD
icon: 💧
ruta_relativa: fisica-clasica/mecanica/fluidos/dinamica-de-fluidos/aplicaciones-de-bernoulli/tubo-de-pitot
descripcion: Medicion de velocidad en conductos.
descripcion_corta: Medicion de velocidad en conductos.
dificultad: 2
tiempo_estimado_min: 55
prerequisitos:
  - fisica-clasica/mecanica/fluidos/dinamica-de-fluidos/ecuacion-de-bernoulli
tags:
  - fluidos
  - aplicaciones-de-bernoulli
  - tubo-de-pitot
graficos:
  - Coord
  - Svg
