id: autoinduccion
titulo: autoinduccion
type: leaf
orden: 2100410
niveles:
  - UNIVERSIDAD
icon: 🏜️
ruta_relativa: fisica-clasica/electromagnetismo/induccion-electromagnetica/inductancia/autoinduccion
descripcion: 'Subtema: Autoinduccion. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
