id: primera-ley-de-la-termodinamica
titulo: primera-ley-de-la-termodinamica
type: leaf
orden: 254300
niveles:
  - ESO
  - BACHILLERATO
  - UNIVERSIDAD
icon: 🌍
ruta_relativa: fisica-clasica/termodinamica/trabajo-y-primera-ley/primera-ley-de-la-termodinamica
descripcion: 'Subtema: Primera Ley de la Termodinamica. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
