#!/usr/bin/env node

/**
 * Script de generación de topics v3 - Usa hierarchy-config.js como referencia
 * Genera el archivo topics.generated.js manteniendo la estructura jerárquica completa
 * PRESERVA LOS EMOJIS existentes en lugar de usar referencias PNG
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { hierarchyConfig } from '../src/config/hierarchy-config.js';
import { emojiMap } from '../src/config/emoji-map.js';
import { iconConfig } from '../src/config/icon-config.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Cargar iconMap.generated.json (fuente principal de iconos)
let iconMap = {};
const ICON_MAP_FILE = path.join(__dirname, '../src/data/iconMap.generated.json');
if (fs.existsSync(ICON_MAP_FILE)) {
  try {
    iconMap = JSON.parse(fs.readFileSync(ICON_MAP_FILE, 'utf8'));
    console.log(`📦 Mapa de iconos cargado: ${Object.keys(iconMap).length} iconos`);
  } catch (err) {
    console.warn('Failed to parse iconMap.generated.json:', err.message);
  }
}

const TOPICS_FILE = path.join(__dirname, '../src/data/topics.generated.js');
const ASSETS_DIR = path.join(__dirname, '../src/assets');

console.log(`📦 Mapa de emojis cargado: ${Object.keys(emojiMap).length} iconos`);

// NOTA: Los iconos ahora se obtienen de icon-config.js (fuente única de verdad)
// Este archivo centraliza todos los iconos para topics y sidebar

// Función simplificada - ya NO genera imports de PNGs
function generateImports() {
  // Solo generar header sin imports
  return `// Auto-generated file - DO NOT EDIT MANUALLY
// Generated by scripts/generateTopicsV3.js using src/config/hierarchy-config.js
// Icons use emojis from emoji-map.js (extracted from teoria.jsx files)
// Run: npm run generate:topics
`;
}

// Mapeo de títulos con tildes correctas
const titleMapping = {
  // Títulos principales
  'clasica': 'Física Clásica',
  'moderna': 'Física Moderna',
  'mecanica': 'Mecánica',
  'termodinamica': 'Termodinámica',
  'electromagnetismo': 'Electromagnetismo',
  'optica': 'Óptica',
  'acustica': 'Acústica',
  'hidrostatica': 'Hidrostática',
  
  // Mecánica
  'cinematica': 'Cinemática',
  'dinamica': 'Dinámica',
  'estatica': 'Estática',
  
  // Estática
  'centro': 'Centro de Masa y Centroide',
  'friccionest': 'Fricción Estática',
  
  // Dinámica
  'movcircular': 'Movimiento Circular',
  'movimpulso': 'Movimiento e Impulso',
  'masaspoleas': 'Masas y Poleas',
  'trabajoenergia': 'Trabajo y Energía',
  
  // Termodinámica - Nivel 0 (ESO)
  '00_calor_temperatura_basicos': 'Calor y Temperatura - Conceptos Básicos',
  'diferencia_calor_temperatura': 'Diferencia entre Calor y Temperatura',
  'cambios_de_estado': 'Cambios de Estado',
  'graficas_temperatura_tiempo': 'Gráficas Temperatura-Tiempo',
  'dilatacion_termica': 'Dilatación Térmica',
  'transferencia_calor_cotidiana': 'Transferencia de Calor Cotidiana',
  'aislantes_conductores': 'Aislantes y Conductores Térmicos',
  
  // Termodinámica - Nivel 1
  '01_conceptos_fundamentales': 'Conceptos Fundamentales',
  'introduccion_a_la_termodinamica': 'Introducción a la Termodinámica',
  'sistemas_termodinamicos': 'Sistemas Termodinámicos',
  'estado_y_equilibrio': 'Estado y Equilibrio',
  'frontera_y_entorno': 'Frontera y Entorno',
  'propiedades_termicas': 'Propiedades Térmicas',
  
  // Termodinámica - Nivel 2
  '02_magnitudes_termicas': 'Magnitudes Térmicas',
  'temperatura': 'Temperatura',
  'calor': 'Calor',
  'trabajo_termodinamico': 'Trabajo Termodinámico',
  'presion': 'Presión',
  
  // Termodinámica - Nivel 3
  '03_principios_de_la_termodinamica': 'Principios de la Termodinámica',
  'cero_principio': 'Principio Cero',
  'primera_ley_de_la_termodinamica': 'Primera Ley',
  'segunda_ley_de_la_termodinamica': 'Segunda Ley',
  'tercera_ley_de_la_termodinamica': 'Tercera Ley',
  'formulaciones_equivalentes': 'Formulaciones Equivalentes',
  
  // Termodinámica - Nivel 4
  '04_modelos_moleculares_y_gases': 'Modelos Moleculares y Gases',
  'teoria_cinetica_de_los_gases': 'Teoría Cinética',
  'gases_ideales': 'Gases Ideales',
  'gases_reales': 'Gases Reales',
  'ecuaciones_de_estado': 'Ecuaciones de Estado',
  
  // Termodinámica - Nivel 5
  '05_entropia': 'Entropía',
  'entropia_y_segunda_ley': 'Entropía y Segunda Ley',
  'interpretacion_estadistica': 'Interpretación Estadística',
  'medicion_y_calculo_de_la_entropia': 'Medición y Cálculo',
  'entropia_en_procesos_reales': 'Entropía en Procesos Reales',
  'entropia_de_mezcla': 'Entropía de Mezcla',
  
  // Termodinámica - Nivel 6
  '06_procesos_termodinamicos': 'Procesos Termodinámicos',
  'proceso_isotermico': 'Proceso Isotérmico',
  'proceso_isobarico': 'Proceso Isobárico',
  'proceso_isocorico': 'Proceso Isocórico',
  'proceso_adiabatico': 'Proceso Adiabático',
  'proceso_politropico': 'Proceso Politrópico',
  'procesos_irreversibles': 'Procesos Irreversibles',
  
  // Termodinámica - Nivel 7
  '07_potenciales_termodinamicos': 'Potenciales Termodinámicos',
  'energia_interna': 'Energía Interna',
  'entalpia': 'Entalpía',
  'energia_libre_helmholtz': 'Energía Libre de Helmholtz',
  'energia_libre_gibbs': 'Energía Libre de Gibbs',
  'relaciones_maxwell': 'Relaciones de Maxwell',
  'criterios_equilibrio': 'Criterios de Espontaneidad',
  
  // Termodinámica - Nivel 8
  '08_maquinas_termicas_y_refrigeracion': 'Máquinas Térmicas y Refrigeración',
  'maquinas_termicas': 'Máquinas Térmicas',
  'refrigeracion_y_bombas_de_calor': 'Refrigeración y Bombas de Calor',
  'ciclo_de_carnot': 'Ciclo de Carnot',
  
  // Termodinámica - Nivel 9
  '09_ciclos_termodinamicos': 'Ciclos Termodinámicos',
  'ciclo_otto': 'Ciclo Otto',
  'ciclo_diesel': 'Ciclo Diesel',
  'ciclo_brayton': 'Ciclo Brayton',
  'ciclo_rankine': 'Ciclo Rankine',
  'ciclo_stirling': 'Ciclo Stirling',
  'ciclo_ericsson': 'Ciclo Ericsson',
  
  // Termodinámica - Nivel 10
  '10_ciclos_combinados': 'Ciclos Combinados',
  'ciclo_de_brayton_rankine': 'Ciclo Brayton-Rankine',
  'cogeneracion': 'Cogeneración',
  'ciclo_de_rankine_con_turbina_de_gas': 'Rankine con Turbina de Gas',
  
  // Termodinámica - Nivel 11
  '11_transferencia_de_calor': 'Transferencia de Calor',
  'conceptos_basicos': 'Conceptos Básicos',
  'conduccion': 'Conducción',
  'conveccion': 'Convección',
  'radiacion': 'Radiación',
  'resistencia_termica_equivalente': 'Resistencia Térmica',
  'intercambiadores_de_calor': 'Intercambiadores de Calor',
  'aislamiento_termico': 'Aislamiento Térmico',
  
  // Termodinámica - Nivel 12
  '12_aplicaciones_practicas': 'Aplicaciones Prácticas',
  'centrales_electricas': 'Centrales Eléctricas',
  'motores_de_combustion_interna': 'Motores de Combustión',
  'sistemas_de_climatizacion': 'Sistemas de Climatización',
  'bombas_termicas_domesticas': 'Bombas Térmicas Domésticas',
  'ciclos_de_potencia': 'Ciclos de Potencia',
  'ciclos_de_refrigeracion': 'Ciclos de Refrigeración',
  
  // Termodinámica - Nivel 13
  '13_termodinamica_estadistica': 'Termodinámica Estadística',
  'microestados_y_macroestados': 'Microestados y Macroestados',
  'distribuciones_de_boltzmann_y_gibbs': 'Distribuciones Estadísticas',
  'funcion_de_particion': 'Función de Partición',
  'ensambles_estadisticos': 'Ensambles Estadísticos',
  'estadisticas_cuanticas': 'Estadísticas Cuánticas',
  'teorema_de_equiparticion': 'Teorema de Equipartición',
  'gas_ideal_cuantico': 'Gas Ideal Cuántico',
  'condensacion_bose_einstein': 'Condensación Bose-Einstein',
  'gas_de_fermi': 'Gas de Fermi',
  'fonones_modelo_debye': 'Fonones - Modelo de Debye',
  'transiciones_de_fase': 'Transiciones de Fase',
  'modelo_de_ising': 'Modelo de Ising',
  'calculo_de_propiedades_termodinamicas': 'Cálculo de Propiedades Termodinámicas',
  'simulaciones_monte_carlo': 'Simulaciones Monte Carlo',
  'aplicaciones_de_la_estadistica_cuantica': 'Aplicaciones de la Estadística Cuántica',
  'analisis_de_sistemas_complejos': 'Análisis de Sistemas Complejos',
  
  // Acústica - ESO
  'ondas_sonoras': 'Ondas Sonoras',
  'propiedades_sonido': 'Propiedades del Sonido',
  'contaminacion_acustica': 'Contaminación Acústica',
  'oido_humano': 'El Oído Humano',
  'proteccion_auditiva': 'Protección Auditiva',
  
  // Acústica - Avanzada
  'resonancia': 'Resonancia',
  'efecto_doppler': 'Efecto Doppler',
  'acustica_arquitectonica': 'Acústica Arquitectónica',
  'psicoacustica': 'Psicoacústica',
  'ultrasonido': 'Ultrasonido',
  'acustica_musical': 'Acústica Musical'
};

// Títulos personalizados para subtemas avanzados
titleMapping['circuitos-avanzados-cc'] = 'Circuitos CC (Avanzado)';
titleMapping['circuitos-avanzados-ca'] = 'Circuitos CA (Avanzado)';

function capitalizeTitle(str) {
  // Primero buscar en el mapeo de títulos
  if (titleMapping[str]) {
    return titleMapping[str];
  }
  
  // Si no está en el mapeo, generar automáticamente
  return str
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, l => l.toUpperCase())
    .replace(/\d+\s+/, match => match); // Mantener números al inicio
}

/**
 * Obtiene el icono para una sección
 * Prioridad: iconMap.generated.json > iconConfig > emojiMap > default
 */
function getIconForSection(sectionKey) {
  // 1. Buscar en iconMap.generated.json (máxima prioridad)
  if (iconMap[sectionKey]) {
    return iconMap[sectionKey];
  }
  
  // 2. Buscar en iconConfig (temas principales sin teoria.jsx)
  if (iconConfig[sectionKey]) {
    return iconConfig[sectionKey];
  }
  
  // 3. Buscar en emojiMap (fallback)
  if (emojiMap[sectionKey]) {
    return emojiMap[sectionKey];
  }
  
  // 4. Default
  return '📚';
}

function generateSection(sectionKey, sectionData, isTopLevel = false) {
  const title = capitalizeTitle(sectionKey);
  const intro = getIntroForSection(sectionKey, isTopLevel);
  
  let cards = [];
  
  if (Array.isArray(sectionData)) {
    // Es una lista de subsecciones
    cards = sectionData.map(subsectionKey => ({
      tipo: subsectionKey,
      titulo: capitalizeTitle(subsectionKey),
      descripcion: getDescriptionForSection(subsectionKey),
      icono: getIconForSection(subsectionKey),
      palette: getPaletteForSection(subsectionKey),
      isTheoryOnly: isTheoryOnlySection(subsectionKey),
      btn: {
        texto: "Explorar",
        clase: `${subsectionKey}-btn`,
        link: generateLinkForSection(sectionKey, subsectionKey)
      }
    }));
  }
  
  return {
    title,
    intro,
    cards,
    additionalContent: getAdditionalContentForSection(sectionKey)
  };
}

function getIntroForSection(sectionKey, isTopLevel = false) {
  // Mapeo de intros para todos los niveles
  const intros = {
    // Top level
    'clasica': "La Física Clásica es la rama de la física que estudia los fenómenos naturales a escalas humanas, es decir, aquellos que ocurren a velocidades mucho menores que la de la luz y en cuerpos de gran tamaño comparados con átomos. Se ocupa de explicar el movimiento, las fuerzas, la energía y el equilibrio de los cuerpos, basándose en leyes formuladas entre los siglos XVII y XIX por científicos como Isaac Newton, Galileo Galilei y James Clerk Maxwell.",
    'moderna': "La física moderna revolucionó nuestra comprensión del universo a escalas muy pequeñas y a velocidades cercanas a la de la luz. Se basa en dos pilares: la teoría de la relatividad de Einstein, que describe el espacio-tiempo y la gravedad, y la mecánica cuántica, que explora el comportamiento de la materia y la energía a nivel atómico y subatómico. Juntas, estas teorías explican desde los agujeros negros hasta el funcionamiento de los láseres y los semiconductores.",
    'mecanica': "La física mecánica es la rama de la física que estudia el movimiento de los cuerpos y las fuerzas que lo producen o lo modifican. Analiza cómo los objetos se desplazan, cómo reaccionan ante fuerzas externas y cómo se comportan en equilibrio o movimiento. Es una de las áreas más antiguas de la física y la base sobre la que se construyen muchas otras disciplinas científicas.",
    'termodinamica': "Estudio de las relaciones entre calor, trabajo, temperatura y energía",
    'electromagnetismo': "Estudio de los fenómenos eléctricos y magnéticos y su interrelación",
    
    // Termodinámica - Niveles
    '01_conceptos_fundamentales': "Definiciones básicas y fundamentos de la termodinámica",
    '02_magnitudes_termicas': "Calor, temperatura y trabajo termodinámico",
    '03_principios_de_la_termodinamica': "Las cuatro leyes fundamentales de la termodinámica",
    '04_modelos_moleculares_y_gases': "Teoría cinética y comportamiento de gases",
    '05_entropia': "Concepto de entropía y sus aplicaciones",
    '06_procesos_termodinamicos': "Procesos isotérmicos, adiabáticos, isobáricos e isocóricos",
    '07_potenciales_termodinamicos': "Funciones de estado y criterios de equilibrio",
    '08_maquinas_termicas_y_refrigeracion': "Motores térmicos y sistemas de refrigeración",
    '09_ciclos_termodinamicos': "Ciclos de potencia y refrigeración",
    '10_ciclos_combinados': "Sistemas de alta eficiencia",
    '11_transferencia_de_calor': "Conducción, convección y radiación",
    '12_aplicaciones_practicas': "Sistemas reales de ingeniería",
    '13_termodinamica_estadistica': "Conexión microscópica-macroscópica",
    
    // Mecánica
    'cinematica': "Estudio del movimiento sin considerar sus causas",
    'dinamica': "Estudio del movimiento y las fuerzas que lo producen",
    'estatica': "Estudio del equilibrio de los cuerpos",
    
    // Electromagnetismo
    'electricidad': "Estudio de cargas eléctricas y campos eléctricos",
    'magnetismo': "Estudio de campos magnéticos e inducción",
    'electronica': "Dispositivos y circuitos electrónicos",
    'ondas': "Ondas electromagnéticas y sus aplicaciones",
    'maxwell': "Ecuaciones fundamentales del electromagnetismo"
  };
  
  // Si existe en el mapeo, usar esa intro
  if (intros[sectionKey]) {
    return intros[sectionKey];
  }
  
  // Si no existe, generar una intro genérica limpia (sin números ni guiones bajos)
  const cleanTitle = capitalizeTitle(sectionKey);
  return `Estudio de ${cleanTitle.toLowerCase()}`;
}

function getDescriptionForSection(sectionKey) {
  // Aquí podrías añadir descripciones específicas para cada sección
  return `Estudio de ${sectionKey.replace(/[-_]/g, ' ').toLowerCase()}`;
}

/**
 * Lee el metadata de un archivo teoria.jsx para obtener isTheoryOnly
 * @param {string} sectionKey - Clave de la sección
 * @returns {boolean} - true si es solo teórico, false si es teórico-práctico
 */
function isTheoryOnlySection(sectionKey) {
  // Intentar encontrar el archivo teoria.jsx correspondiente
  const possiblePaths = [
    // Buscar en todas las carpetas principales
    `src/data/metodo_cientifico/${sectionKey}/teoria.jsx`,
    `src/data/mecanica/${sectionKey}/teoria.jsx`,
    `src/data/mecanica/cinematica/${sectionKey}/teoria.jsx`,
    `src/data/mecanica/cinematica/introduccion_movimiento/${sectionKey}/teoria.jsx`,
    `src/data/mecanica/dinamica/${sectionKey}/teoria.jsx`,
    `src/data/mecanica/dinamica/introduccion_dinamica/${sectionKey}/teoria.jsx`,
    `src/data/mecanica/dinamica/colisiones/${sectionKey}/teoria.jsx`,
    `src/data/mecanica/dinamica/maquinas_simples/${sectionKey}/teoria.jsx`,
    `src/data/mecanica/dinamica/energia_cotidiana/${sectionKey}/teoria.jsx`,
    `src/data/mecanica/dinamica/energia_cotidiana/fuentes_energia/${sectionKey}/teoria.jsx`,
    `src/data/mecanica/estatica/${sectionKey}/teoria.jsx`,
    `src/data/mecanica/ondas_mecanicas/${sectionKey}/teoria.jsx`,
    `src/data/mecanica/mecanica_analitica/${sectionKey}/teoria.jsx`,
    `src/data/termodinamica/${sectionKey}/teoria.jsx`,
    `src/data/termodinamica/00_calor_temperatura_basicos/${sectionKey}/teoria.jsx`,
    `src/data/termodinamica/01_conceptos_fundamentales/${sectionKey}/teoria.jsx`,
    `src/data/termodinamica/02_magnitudes_termicas/${sectionKey}/teoria.jsx`,
    `src/data/termodinamica/03_principios_de_la_termodinamica/${sectionKey}/teoria.jsx`,
    `src/data/termodinamica/04_modelos_moleculares_y_gases/${sectionKey}/teoria.jsx`,
    `src/data/termodinamica/05_entropia/${sectionKey}/teoria.jsx`,
    `src/data/termodinamica/06_procesos_termodinamicos/${sectionKey}/teoria.jsx`,
    `src/data/termodinamica/07_potenciales_termodinamicos/${sectionKey}/teoria.jsx`,
    `src/data/termodinamica/08_maquinas_termicas_y_refrigeracion/${sectionKey}/teoria.jsx`,
    `src/data/termodinamica/09_ciclos_termodinamicos/${sectionKey}/teoria.jsx`,
    `src/data/termodinamica/10_ciclos_combinados/${sectionKey}/teoria.jsx`,
    `src/data/termodinamica/11_transferencia_de_calor/${sectionKey}/teoria.jsx`,
    `src/data/termodinamica/12_aplicaciones_practicas/${sectionKey}/teoria.jsx`,
    `src/data/termodinamica/13_termodinamica_estadistica/${sectionKey}/teoria.jsx`,
    `src/data/mecanica_de_fluidos/${sectionKey}/teoria.jsx`,
    `src/data/mecanica_de_fluidos/estatica_de_fluidos/${sectionKey}/teoria.jsx`,
    `src/data/mecanica_de_fluidos/flujo_compresible/${sectionKey}/teoria.jsx`,
    `src/data/introduccion_fluidos/${sectionKey}/teoria.jsx`,
    `src/data/introduccion_fluidos/aplicaciones_cotidianas/${sectionKey}/teoria.jsx`,
    `src/data/optica/${sectionKey}/teoria.jsx`,
    // Óptica - subcarpetas comunes (nested)
    `src/data/optica/introduccion_luz/${sectionKey}/teoria.jsx`,
    `src/data/optica/reflexion_basica/${sectionKey}/teoria.jsx`,
    `src/data/optica/refraccion_basica/${sectionKey}/teoria.jsx`,
    `src/data/optica/colores_y_espectro/${sectionKey}/teoria.jsx`,
    `src/data/optica/vision_y_ojo_humano/${sectionKey}/teoria.jsx`,
    `src/data/optica/aplicaciones_cotidianas_optica/${sectionKey}/teoria.jsx`,
    `src/data/optica/optica_geometrica/${sectionKey}/teoria.jsx`,
    `src/data/optica/optica_fisica/${sectionKey}/teoria.jsx`,
    `src/data/optica/fotometria/${sectionKey}/teoria.jsx`,
    `src/data/electromagnetismo/${sectionKey}/teoria.jsx`,
    `src/data/electromagnetismo/magnetismo/magnetismo-basico/${sectionKey}/teoria.jsx`,
    `src/data/electromagnetismo/electricidad/${sectionKey}/teoria.jsx`,
    `src/data/electromagnetismo/electronica/${sectionKey}/teoria.jsx`,
    `src/data/acustica/${sectionKey}/teoria.jsx`,
    `src/data/fisica_plasmas/${sectionKey}/teoria.jsx`,
    `src/data/teoria_campos_clasicos/${sectionKey}/teoria.jsx`,
  ];

  for (const relativePath of possiblePaths) {
    const fullPath = path.join(__dirname, '..', relativePath);
    if (fs.existsSync(fullPath)) {
      try {
        const content = fs.readFileSync(fullPath, 'utf8');
        // Buscar el campo isTheoryOnly en el metadata
        const metadataMatch = content.match(/export\s+const\s+metadata\s*=\s*\{([^}]+)\}/s);
        if (metadataMatch) {
          const metadataContent = metadataMatch[1];
          const isTheoryOnlyMatch = metadataContent.match(/isTheoryOnly\s*:\s*(true|false)/);
          if (isTheoryOnlyMatch) {
            return isTheoryOnlyMatch[1] === 'true';
          }
        }
      } catch (err) {
        // Si hay error leyendo el archivo, continuar con el siguiente
      }
    }
  }

  // Por defecto, si no se encuentra el archivo o no tiene isTheoryOnly, es teórico-práctico
  return false;
}

function getPaletteForSection(sectionKey) {
  // Color naranja para subtemas únicamente teóricos
  if (isTheoryOnlySection(sectionKey)) {
    return 'orange';
  }
  // Color por defecto azul para todos los demás temas
  return 'blue';
}

function generateLinkForSection(parentKey, sectionKey) {
  // Generar enlaces basados en la jerarquía
  if (parentKey === 'main') return `/${sectionKey}`;
  if (parentKey === 'clasica') return `/clasica/${sectionKey}`;
  
  // Detectar si el parentKey es un subtema de termodinámica
  const thermodynamicsTopics = [
    '01_conceptos_fundamentales',
    '02_magnitudes_termicas',
    '03_principios_de_la_termodinamica',
    '04_modelos_moleculares_y_gases',
    '05_entropia',
    '06_procesos_termodinamicos',
    '07_potenciales_termodinamicos',
    '08_maquinas_termicas_y_refrigeracion',
    '09_ciclos_termodinamicos',
    '10_ciclos_combinados',
    '11_transferencia_de_calor',
    '12_aplicaciones_practicas',
    '13_termodinamica_estadistica'
  ];
  
  if (thermodynamicsTopics.includes(parentKey)) {
    return `/clasica/termodinamica/${parentKey}/${sectionKey}`;
  }
  
  // Detectar si el parentKey es 'circuitos' (subtema de electricidad)
  if (parentKey === 'circuitos') {
    return `/clasica/electromagnetismo/electricidad/circuitos/${sectionKey}`;
  }
  
  // Detectar si el parentKey es un subtema de electromagnetismo
  const electromagnetismoTopics = [
    'electricidad',
    'magnetismo',
    'electronica',
    'ondas',
    'maxwell'
  ];
  
  if (electromagnetismoTopics.includes(parentKey)) {
    return `/clasica/electromagnetismo/${parentKey}/${sectionKey}`;
  }

  // Detectar si el parentKey es 'circuitos-avanzados' (página índice con subcards)
  if (parentKey === 'circuitos-avanzados') {
    // sectionKey expected like 'circuitos-avanzados-cc' or 'circuitos-avanzados-ca'
    const sub = sectionKey.replace(/^circuitos-avanzados-/, '');
    return `/clasica/electromagnetismo/electricidad/circuitos/circuitos-avanzados/${sub}`;
  }
  
  // Detectar si el parentKey es un subtema de mecánica
  const mecanicaTopics = [
    'cinematica',
    'dinamica',
    'estatica',
    'mecanica_analitica',
    'ondas_mecanicas'
  ];
  
  if (mecanicaTopics.includes(parentKey)) {
    return `/clasica/mecanica/${parentKey}/${sectionKey}`;
  }

  // Detectar si el parentKey es un subtema de estática
  const estaticaTopics = [
    'elasticidad_deformacion'
  ];
  
  if (estaticaTopics.includes(parentKey)) {
    return `/clasica/mecanica/estatica/${parentKey}/${sectionKey}`;
  }

  // Detectar si el parentKey es un subtema de cinemática
  const cinematicaTopics = [
    'introduccion_movimiento'
  ];
  
  if (cinematicaTopics.includes(parentKey)) {
    return `/clasica/mecanica/cinematica/${parentKey}/${sectionKey}`;
  }

  // Detectar si el parentKey es un subtema de dinámica
  const dinamicaTopics = [
    'introduccion_dinamica',
    'colisiones',
    'maquinas_simples',
    'energia_cotidiana'
  ];
  
  if (dinamicaTopics.includes(parentKey)) {
    return `/clasica/mecanica/dinamica/${parentKey}/${sectionKey}`;
  }

  // Detectar si el parentKey es un subtema de mecánica analítica
  const mecanicaAnaliticaTopics = [
    'mecanica_analitica'
  ];
  
  if (mecanicaAnaliticaTopics.includes(parentKey)) {
    return `/clasica/mecanica/mecanica_analitica/${sectionKey}`;
  }

  // Detectar si el parentKey es un subtema de óptica
  const opticaTopics = [
    'optica_geometrica',
    'optica_fisica',
    'fotometria'
  ];
  
  if (opticaTopics.includes(parentKey)) {
    return `/clasica/optica/${parentKey}/${sectionKey}`;
  }
  
  // Por defecto
  return `/clasica/${parentKey}/${sectionKey}`;
}

function getAdditionalContentForSection(sectionKey) {
  if (sectionKey === 'mecanica') {
    return "\n        <h3>Comparativa rápida</h3>\n        <ul>\n          <li><b>Cinemática:</b> Describe el movimiento sin analizar sus causas.</li>\n          <li><b>Dinámica:</b> Explica el movimiento considerando las fuerzas que lo producen.</li>\n          <li><b>Estática:</b> Estudia el equilibrio de los cuerpos y las fuerzas en reposo.</li>\n        </ul>\n      ";
  }
  return "";
}

function generateTopicsData() {
  const topicsData = {};
  
  // Agregar entrada raíz para la página principal
  topicsData[""] = {
    title: "Física - Ciencia del Universo",
    intro: "La física es la ciencia natural que estudia las propiedades fundamentales de la materia, la energía, el tiempo y el espacio, así como las interacciones entre ellos.",
    cards: [
      {
        tipo: "clasica",
        titulo: "Física Clásica",
        descripcion: "Mecánica, Termodinámica, Óptica, Electromagnetismo...",
        icono: emojiMap['clasica'] || "m_clasica",
        btn: {
          texto: "Explorar",
          clase: "clasica",
          link: "/clasica"
        }
      },
      {
        tipo: "moderna",
        titulo: "Física Moderna",
        descripcion: "Relatividad, Cuántica, Física de partículas...",
        icono: emojiMap['moderna'] || "m_moderna",
        btn: {
          texto: "Explorar",
          clase: "moderna",
          link: "/moderna"
        }
      }
    ],
    additionalContent: ""
  };
  
  // Generar todas las secciones basadas en hierarchyConfig
  for (const [sectionKey, sectionData] of Object.entries(hierarchyConfig)) {
    if (sectionKey === 'main') continue; // Skip main
    if (sectionKey === 'optica') {
      console.log('🔍 Óptica hierarchy entries:', Array.isArray(sectionData) ? sectionData.join(', ') : sectionData);
    }
    
    // Generar la sección padre
    topicsData[sectionKey] = generateSection(sectionKey, sectionData, 
      ['clasica', 'moderna', 'mecanica', 'termodinamica', 'electromagnetismo'].includes(sectionKey)
    );
    
    // Generar todas las subsecciones si existen
    if (Array.isArray(sectionData)) {
      for (const childSection of sectionData) {
        // Solo generar si no existe ya (evitar duplicados)
        if (!topicsData[childSection]) {
          // Verificar si este childSection tiene sus propios hijos en hierarchyConfig
          const childData = hierarchyConfig[childSection];
          topicsData[childSection] = generateSection(childSection, childData || [], false);
          
          // Si el childSection tiene hijos, generarlos también
          if (Array.isArray(childData)) {
            for (const grandchildSection of childData) {
              if (!topicsData[grandchildSection]) {
                // Verificar si este grandchild tiene sus propios hijos
                const grandchildData = hierarchyConfig[grandchildSection];
                topicsData[grandchildSection] = generateSection(grandchildSection, grandchildData || [], false);
                
                // Si el grandchild tiene hijos, generarlos también (nivel 4)
                if (Array.isArray(grandchildData)) {
                  for (const greatGrandchildSection of grandchildData) {
                    if (!topicsData[greatGrandchildSection]) {
                      topicsData[greatGrandchildSection] = generateSection(greatGrandchildSection, [], false);
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  
  // Agregar sección 'moderna' si no existe
  if (!topicsData['moderna']) {
    topicsData['moderna'] = generateSection('moderna', [], false);
  }
  
  return topicsData;
}

function generateMainExports() {
  // Usar emojis si están disponibles, si no usar variables PNG
  const clasicaIcon = emojiMap['clasica'] ? `"${emojiMap['clasica']}"` : 'm_clasica';
  const modernaIcon = emojiMap['moderna'] ? `"${emojiMap['moderna']}"` : 'm_moderna';
  
  return `
export const temasFisica = [
  {
    tipo: "clasica",
    titulo: "Física Clásica",
    descripcion: "Mecánica, Termodinámica, Óptica, Electromagnetismo...",
    icono: ${clasicaIcon},
    btn: {
      texto: "Explorar",
      clase: "clasica",
      link: "/clasica",
    },
  },
  {
    tipo: "moderna",
    titulo: "Física Moderna",
    descripcion: "Relatividad, Cuántica, Física de partículas...",
    icono: ${modernaIcon},
    btn: {
      texto: "Explorar",
      clase: "moderna",
      link: "/moderna",
    },
  },
];
`;
}

function generateCompleteFile() {
  console.log('🔧 Generando topics.generated.js usando hierarchy-config.js...');
  
  const imports = generateImports();
  const mainExports = generateMainExports();
  const topicsData = generateTopicsData();
  
  let content = imports + mainExports;
  content += '\nexport const topicsData = {\n';
  
  const sections = Object.entries(topicsData);
  sections.forEach(([key, data], index) => {
    content += `  "${key}": ${JSON.stringify(data, null, 4)}`;
    if (index < sections.length - 1) {
      content += ',';
    }
    content += '\n';
  });
  
  content += '};\n';
  
  // Fix icon references - replace string references with actual variables
  // PERO solo para referencias PNG, NO para emojis
  content = content.replace(/"icono": "([a-zA-Z_]+Icon)"/g, '"icono": $1');
  content = content.replace(/"icono": "m_clasica"/g, '"icono": m_clasica');
  content = content.replace(/"icono": "m_moderna"/g, '"icono": m_moderna');
  
  console.log(`✨ Emojis preservados: ${Object.keys(emojiMap).length} iconos mantienen formato emoji`);
  
  return content;
}

// Generar el archivo
try {
  const content = generateCompleteFile();
  fs.writeFileSync(TOPICS_FILE, content, 'utf8');
  console.log(`✅ Archivo ${TOPICS_FILE} generado exitosamente`);
  console.log(`📊 Secciones generadas: ${Object.keys(hierarchyConfig).length - 1}`); // -1 para excluir 'main'
} catch (error) {
  console.error('❌ Error generando el archivo:', error.message);
  process.exit(1);
}