from __future__ import annotations

from pathlib import Path

ES_TEMPLATES = [
    lambda concept, s: f"## {{num}}. {s['title_es']}\n\nEn {s['place_es']}, {concept} sirve para {s['decision_es']}. La utilidad real aparece cuando hay que convertir una observacion parcial en un criterio operativo: decidir si el sistema puede tratarse con el modelo del leaf, si conviene recortar el intervalo de analisis y que dato experimental manda cuando varias explicaciones parecen posibles. En lugar de repetir una formula, la aplicacion obliga a identificar donde entra el intercambio de momento, como se mide y por que el resultado cambia cuando el escenario deja de parecerse al ideal.\n\nLa lectura buena no se cierra con la cuenta. Tambien exige comparar el orden de magnitud esperado con lo que muestran sensores, video o trazas sobre el banco de ensayo. Si el valor obtenido solo funciona despues de ignorar una fuerza, una deformacion o una geometria dominante, entonces la decision tecnica debe cambiar. Por eso en {s['place_es']} la interpretacion se usa para justificar una accion concreta y no para decorar la solucion.",
    lambda concept, s: f"## {{num}}. {s['title_es']}\n\nCuando se analiza {s['place_es']}, la relevancia de {concept} aparece al tener que {s['decision_es']}. Lo primero es separar sistema, entorno y ventana temporal, porque un mismo montaje puede parecer favorable al modelo del leaf durante el contacto principal y dejar de serlo unos instantes despues. Esa distincion cambia que datos conviene tomar, que magnitudes deben proyectarse y que comparaciones permiten defender la conclusion ante otra persona.\n\nEn esta aplicacion no basta con que el calculo sea limpio. Hay que revisar si el dato dominante viene de una velocidad relativa, de una masa efectiva, de un angulo o de una fuerza externa acumulada en poco tiempo. Tambien hay que mirar que perturbacion volveria enganoso el resultado: rozamiento, giro, acoplamiento estructural, flexion o mala definicion del sistema. Si ese limite no se explicita, la prediccion puede parecer razonable y aun asi conducir a una decision equivocada.",
    lambda concept, s: f"## {{num}}. {s['title_es']}\n\nUna aplicacion exigente de {concept} aparece en {s['place_es']}. Ahi no interesa una descripcion escolar generica, sino resolver {s['decision_es']} con un criterio que pueda contrastarse. Eso obliga a traducir la teoria a operaciones observables: fijar ejes, escoger el antes y el despues del proceso, descartar interacciones secundarias solo cuando su impulso o su efecto energetico sean realmente pequenos y relacionar el modelo con una medida disponible en el problema.\n\nEl valor didactico del caso esta en que muestra donde suele romperse la intuicion. Una lectura apresurada suele mezclar fuerzas internas con externas, usar datos tomados fuera del intervalo util o confundir simetria geometrica con validez dinamica. Por eso el cierre debe decir que magnitud gobierna la decision, que evidencia experimental la respalda y que cambio del entorno obligaria a sustituir el modelo por otro mas completo. Esa ultima frase es la que convierte la aplicacion en una herramienta de trabajo.",
    lambda concept, s: f"## {{num}}. {s['title_es']}\n\nEn {s['place_es']}, {concept} deja de ser abstracto porque permite {s['decision_es']}. El problema practico no consiste solo en obtener un numero, sino en decidir si la simplificacion elegida sigue siendo defendible cuando aparecen tiempos finitos de contacto, rotaciones, apoyos o distribuciones reales de masa. Para responder bien hay que conectar el modelo con una escena medible y con una consecuencia tangible: aprobar un ensayo, corregir un diseno, interpretar un video o rechazar una conclusion precipitada.\n\nEsta clase de aplicacion obliga a mirar el proceso en dos capas. Primero, la capa mecanica que fija que magnitudes son nucleares y que conservaciones siguen activas. Despues, la capa de validacion, donde se comprueba si el montaje introduce una fuerza externa, una disipacion o una restriccion geometrica suficiente para alterar la lectura. Si se omite esa segunda capa, el numero final puede ser internamente coherente y, aun asi, inutil para actuar sobre el sistema real.",
    lambda concept, s: f"## {{num}}. {s['title_es']}\n\nLa interpretacion de {concept} es decisiva en {s['place_es']} cuando toca {s['decision_es']}. La escena obliga a elegir entre varias historias fisicas posibles y a quedarse solo con la que mantiene consistencia entre diagrama, escala temporal y dato disponible. Por eso la aplicacion no se resuelve citando la ley; se resuelve justificando que variable se mide primero, cual puede inferirse y que aproximacion permite pasar del montaje real a una prediccion util.\n\nTambien es una buena prueba de madurez porque el error tipico no suele ser algebraico, sino de encuadre. Si se toma mal el sistema, si se mezclan fases distintas del proceso o si se extrapola una condicion ideal mas alla de su rango, la lectura se vuelve fragil. Explicar ese punto de ruptura es obligatorio: solo asi puede distinguirse entre un resultado que sirve para decidir y un ejemplo que solo ilustra una tendencia general.",
]

EN_TEMPLATES = [
    lambda concept, s: f"## {{num}}. {s['title_en']}\n\nIn {s['place_en']}, {concept} is used to {s['decision_en']}. Its value appears when a partial observation has to become an operational criterion: deciding whether the system can still be described with the leaf model, whether the time window must be shortened, and which measured quantity actually governs the interpretation. Instead of repeating a formula, the application forces the reader to identify where momentum exchange enters, how it is measured, and why the result changes once the setup stops resembling the ideal case.\n\nThe reasoning cannot stop at the calculation. It also has to compare the expected scale with what sensors, video, or traces on the test bench really show. If the result works only after ignoring a dominant force, deformation, or geometric constraint, then the technical decision has to change as well. That is why the interpretation in {s['place_en']} supports a concrete action rather than decorating the solution.",
    lambda concept, s: f"## {{num}}. {s['title_en']}\n\nWhen {s['place_en']} is studied, the usefulness of {concept} appears in the need to {s['decision_en']}. The first step is to separate system, surroundings, and time window, because the same setup may fit the leaf model during the main interaction and stop fitting it a moment later. That distinction changes which data should be recorded, which quantities have to be projected, and which comparisons can defend the conclusion in front of someone else.\n\nA clean calculation is not enough here. One must decide whether the governing datum comes from a relative speed, an effective mass, an angle, or an external force accumulated over a short interval. One must also state which disturbance would make the result misleading: friction, spin, structural coupling, flexure, or a poor system definition. If that limit is left implicit, the prediction may look reasonable and still support the wrong decision.",
    lambda concept, s: f"## {{num}}. {s['title_en']}\n\nA demanding use of {concept} appears in {s['place_en']}. The goal is not a generic school description but to solve {s['decision_en']} with a criterion that can be checked. That forces theory to be translated into observable operations: fix axes, choose the before and after states, discard secondary interactions only when their impulse or energetic effect is actually small, and connect the model with a quantity that can truly be measured in the problem.\n\nThe didactic value of the case is that it shows where intuition usually breaks. A rushed reading tends to mix internal and external forces, use data outside the useful interval, or confuse geometric symmetry with dynamical validity. The closing interpretation therefore has to say which quantity governs the decision, which experimental evidence supports it, and which environmental change would force a different model. That last sentence is what turns the application into a working tool.",
    lambda concept, s: f"## {{num}}. {s['title_en']}\n\nIn {s['place_en']}, {concept} stops being abstract because it allows one to {s['decision_en']}. The practical task is not only to obtain a number, but to decide whether the chosen simplification remains defensible once finite contact times, rotations, supports, or real mass distributions appear. A good answer therefore connects the model with a measurable scene and with a tangible consequence: approving a test, correcting a design, interpreting a video, or rejecting a premature conclusion.\n\nThis kind of application has to be read in two layers. First comes the mechanical layer, which fixes the core quantities and the conservation laws that remain active. Then comes the validation layer, where one checks whether the setup introduces an external force, dissipation, or a geometric restriction large enough to modify the reading. If that second layer is skipped, the final number can be internally consistent and still useless for acting on the real system.",
    lambda concept, s: f"## {{num}}. {s['title_en']}\n\nThe interpretation of {concept} becomes decisive in {s['place_en']} when the task is to {s['decision_en']}. The scene forces a choice between several possible physical stories, keeping only the one that stays consistent with the diagram, the time scale, and the available data. For that reason the application is not solved by quoting the law; it is solved by justifying which quantity should be measured first, which one can be inferred, and which approximation turns the real setup into a useful prediction.\n\nIt is also a good maturity test because the typical error is not algebraic but contextual. If the system is chosen badly, if different phases of the process are mixed, or if an ideal condition is extrapolated beyond its range, the interpretation becomes fragile. Stating that breaking point is mandatory, because only then can one distinguish between a result that supports a decision and an example that merely illustrates a trend.",
]


def render_es(entry: dict) -> str:
    chunks = []
    for idx, scenario in enumerate(entry["scenarios"], start=1):
        body = ES_TEMPLATES[idx - 1](entry["concept_es"], scenario).replace("{num}", str(idx))
        body += (
            f"\n\nVariable dominante: {scenario['variable_es']}."
            f"\n\nLimite de validez: {scenario['limit_es']}.\n"
        )
        chunks.append(body)
    return "\n".join(chunks).strip() + "\n"


def render_en(entry: dict) -> str:
    chunks = []
    for idx, scenario in enumerate(entry["scenarios"], start=1):
        body = EN_TEMPLATES[idx - 1](entry["concept_en"], scenario).replace("{num}", str(idx))
        body += (
            f"\n\nDominant variable: {scenario['variable_en']}."
            f"\n\nValidity limit: {scenario['limit_en']}.\n"
        )
        chunks.append(body)
    return "\n".join(chunks).strip() + "\n"


def write_leafs(configs: dict[str, dict]) -> None:
    for rel_path, entry in configs.items():
        leaf_dir = Path(rel_path)
        (leaf_dir / "aplicaciones.md").write_text(render_es(entry), encoding="utf-8")
        (leaf_dir / "aplicaciones.en.md").write_text(render_en(entry), encoding="utf-8")
        print(f"updated {leaf_dir}")


FUNDAMENTOS_CONFIGS = {
    "frontend/src/data_v2_i18n/fisica-clasica/mecanica/cantidad-de-movimiento/fundamentos/impulso": {
        "concept_es": "impulso",
        "concept_en": "impulse",
        "scenarios": [
            {
                "title_es": "Ensayo de acolchado en choque",
                "title_en": "Crash padding test",
                "place_es": "un banco de choque con espuma y soporte rigido",
                "place_en": "a crash bench with foam and a rigid stop",
                "decision_es": "decidir que espesor de acolchado reduce la fuerza media sin perder el frenado requerido",
                "decision_en": "decide which padding thickness lowers average force without losing the required stopping effect",
                "variable_es": "comparar como cambia Fmed cuando el mismo DeltaP se reparte en distintos dt",
                "variable_en": "compare how Fmed changes when the same DeltaP is distributed over different dt values",
                "limit_es": "el modelo deja de bastar si la espuma introduce rebote, rotacion o tiempos de contacto mal definidos",
                "limit_en": "the model stops being enough when the foam introduces rebound, rotation, or poorly defined contact times",
            },
            {
                "title_es": "Ajuste de golpe deportivo",
                "title_en": "Sports impact tuning",
                "place_es": "la lectura de una raqueta o un bate instrumentado",
                "place_en": "the reading of an instrumented racket or bat",
                "decision_es": "elegir si conviene aumentar tiempo de contacto o velocidad de salida para mejorar control",
                "decision_en": "choose whether increasing contact time or exit speed improves control",
                "variable_es": "seguir que parte del rendimiento viene de DeltaP y que parte de la redistribucion temporal del contacto",
                "variable_en": "track which part of performance comes from DeltaP and which part comes from the temporal redistribution of contact",
                "limit_es": "hay que abandonar la lectura simple cuando la flexion del material y la rotacion dominan sobre la traslacion",
                "limit_en": "the simple reading must be abandoned when material flexure and rotation dominate over translation",
            },
            {
                "title_es": "Calibracion de sensor de fuerza",
                "title_en": "Force sensor calibration",
                "place_es": "un laboratorio con celda de carga y camara rapida",
                "place_en": "a lab with a load cell and a high-speed camera",
                "decision_es": "comprobar si el area medida bajo F(t) coincide con el cambio de momento observado en video",
                "decision_en": "check whether the measured area under F(t) matches the momentum change seen on video",
                "variable_es": "usar J como criterio de coherencia entre dos mediciones independientes del mismo evento",
                "variable_en": "use J as a coherence criterion between two independent measurements of the same event",
                "limit_es": "la comparacion falla si el video no captura el mismo intervalo dt o si el eje de medida no coincide",
                "limit_en": "the comparison fails if the video does not capture the same dt interval or if the measurement axis does not match",
            },
            {
                "title_es": "Prueba de embalaje industrial",
                "title_en": "Industrial packaging test",
                "place_es": "un ensayo de caida para cajas con producto fragil",
                "place_en": "a drop test for boxes carrying fragile products",
                "decision_es": "evaluar si el embalaje disipa el impacto alargando el contacto antes de aprobar el diseno",
                "decision_en": "evaluate whether the packaging softens the impact by lengthening contact before approving the design",
                "variable_es": "mirar si el embalaje cambia principalmente dt o si tambien altera el DeltaP final del paquete",
                "variable_en": "check whether the packaging mainly changes dt or also alters the final DeltaP of the package",
                "limit_es": "la lectura deja de ser valida si hay vuelco, multiples impactos o transferencia de energia a partes internas no controladas",
                "limit_en": "the reading stops being valid when there is tipping, multiple impacts, or uncontrolled energy transfer to internal parts",
            },
            {
                "title_es": "Proteccion en caida humana",
                "title_en": "Human fall protection",
                "place_es": "el analisis de colchonetas, arneses y suelos amortiguados",
                "place_en": "the analysis of mats, harnesses, and cushioned floors",
                "decision_es": "decidir que dispositivo reduce mejor la carga sobre el cuerpo para una misma llegada",
                "decision_en": "decide which device better reduces body load for the same incoming motion",
                "variable_es": "priorizar cuanto se reduce Fmed sin perder la capacidad de detener el cuerpo con seguridad",
                "variable_en": "prioritize how much Fmed is reduced without losing the ability to stop the body safely",
                "limit_es": "hay que ir mas alla del leaf si aparecen deformaciones complejas del cuerpo o varias fases de impacto encadenadas",
                "limit_en": "one must go beyond the leaf when complex body deformations or several chained impact phases appear",
            },
        ],
    },
    "frontend/src/data_v2_i18n/fisica-clasica/mecanica/cantidad-de-movimiento/fundamentos/momento-lineal": {
        "concept_es": "momento lineal",
        "concept_en": "linear momentum",
        "scenarios": [
            {
                "title_es": "Comparacion de carros en carril",
                "title_en": "Track cart comparison",
                "place_es": "un ensayo con carros de masas distintas sobre un carril recto",
                "place_en": "a test with carts of different masses on a straight track",
                "decision_es": "decidir que carro sera mas dificil de detener o desviar bajo la misma accion externa",
                "decision_en": "decide which cart will be harder to stop or deflect under the same external action",
                "variable_es": "comparar como p cambia cuando crece m frente a cuando crece v manteniendo el resto del montaje",
                "variable_en": "compare how p changes when m grows versus when v grows while the rest of the setup is held fixed",
                "limit_es": "la comparacion se rompe si se mezclan marcos de referencia o si el rozamiento cambia entre pruebas",
                "limit_en": "the comparison breaks down when reference frames are mixed or friction changes between runs",
            },
            {
                "title_es": "Aproximacion de dron",
                "title_en": "Drone approach reading",
                "place_es": "la maniobra de un dron que entra con componente horizontal y vertical",
                "place_en": "the maneuver of a drone entering with horizontal and vertical components",
                "decision_es": "elegir que componente del movimiento exige correccion prioritaria antes del aterrizaje",
                "decision_en": "choose which motion component requires priority correction before landing",
                "variable_es": "mirar px y py por separado para no confundir modulo con direccion efectiva de entrada",
                "variable_en": "inspect px and py separately so that magnitude is not confused with actual approach direction",
                "limit_es": "la lectura simple deja de bastar si el giro, el empuje variable o el viento dominan sobre la traslacion",
                "limit_en": "the simple reading stops being enough when rotation, variable thrust, or wind dominate over translation",
            },
            {
                "title_es": "Frenado de pallet en almacen",
                "title_en": "Warehouse pallet braking",
                "place_es": "la llegada de un pallet a un tope o a una zona de frenado",
                "place_en": "the arrival of a pallet at a stop or braking zone",
                "decision_es": "dimensionar la maniobra de frenado segun el momento que lleva la carga",
                "decision_en": "size the braking maneuver according to the momentum carried by the load",
                "variable_es": "identificar si la dificultad viene del aumento de masa total o del incremento de velocidad de entrada",
                "variable_en": "identify whether the difficulty comes from the larger total mass or from the higher incoming speed",
                "limit_es": "el modelo necesita ampliarse cuando hay deformacion del pallet, pendiente o distribucion de masa muy desigual",
                "limit_en": "the model needs to be extended when pallet deformation, slope, or a very uneven mass distribution appears",
            },
            {
                "title_es": "Lectura balistica elemental",
                "title_en": "Elementary ballistic reading",
                "place_es": "una comparacion entre proyectiles ligeros y cuerpos mucho mas masivos",
                "place_en": "a comparison between light projectiles and much more massive bodies",
                "decision_es": "distinguir que parte del riesgo proviene del momento y que parte debe atribuirse a otras magnitudes",
                "decision_en": "distinguish which part of the risk comes from momentum and which part must be assigned to other quantities",
                "variable_es": "usar p como filtro inicial para no equiparar de forma ingenua masa grande con dano grande",
                "variable_en": "use p as a first filter so that large mass is not naively equated with large damage",
                "limit_es": "la lectura no basta cuando se necesita detalle energetico, penetracion o deformacion del blanco",
                "limit_en": "the reading is not enough when energetic detail, penetration, or target deformation is required",
            },
            {
                "title_es": "Seguimiento de video en dos ejes",
                "title_en": "Two-axis video tracking",
                "place_es": "el analisis de una trayectoria grabada desde laboratorio o campo",
                "place_en": "the analysis of a trajectory recorded in lab or field conditions",
                "decision_es": "decidir si la reconstruccion del movimiento es coherente antes de usarla en un informe",
                "decision_en": "decide whether the reconstructed motion is coherent before using it in a report",
                "variable_es": "vigilar la consistencia entre p, px, pf y DeltaP cuando cambian escala, ejes o calibracion",
                "variable_en": "watch the consistency between p, px, pf, and DeltaP when scale, axes, or calibration change",
                "limit_es": "hay que abandonar la lectura si la camara introduce perspectiva fuerte o si falta sincronizacion temporal",
                "limit_en": "the reading must be abandoned when the camera introduces strong perspective effects or time synchronization is missing",
            },
        ],
    },
    "frontend/src/data_v2_i18n/fisica-clasica/mecanica/cantidad-de-movimiento/fundamentos/sistemas-aislados": {
        "concept_es": "sistemas aislados",
        "concept_en": "isolated systems",
        "scenarios": [
            {
                "title_es": "Colision en carril de aire",
                "title_en": "Air-track collision",
                "place_es": "un laboratorio con carros sobre carril de rozamiento muy bajo",
                "place_en": "a lab with carts on a very low-friction air track",
                "decision_es": "decidir si el montaje permite tratar el sistema como aislado antes de aplicar conservacion",
                "decision_en": "decide whether the setup can be treated as isolated before applying conservation",
                "variable_es": "comparar el impulso externo esperado con el intercambio interno del choque",
                "variable_en": "compare the expected external impulse with the internal exchange of the collision",
                "limit_es": "la hipotesis cae si el rozamiento residual, la pendiente o el empuje del aire dejan de ser pequenos",
                "limit_en": "the hypothesis fails when residual friction, slope, or airflow cease to be small",
            },
            {
                "title_es": "Explosion de puck sobre hielo",
                "title_en": "Ice puck explosion",
                "place_es": "una demostracion donde un objeto se separa en fragmentos sobre hielo",
                "place_en": "a demonstration in which one object separates into fragments on ice",
                "decision_es": "comprobar si la lectura de aislamiento sigue siendo defendible durante toda la separacion",
                "decision_en": "check whether the isolation reading remains defensible throughout the separation",
                "variable_es": "vigilar si pTotI y pTotF se mantienen coherentes mientras Jext sigue siendo despreciable",
                "variable_en": "watch whether pTotI and pTotF remain coherent while Jext stays negligible",
                "limit_es": "la aplicacion deja de servir si el objeto roza bordes, recibe un empuje externo o cambia de plano",
                "limit_en": "the application stops working if the object hits boundaries, receives an external push, or changes plane",
            },
            {
                "title_es": "Separacion de nave y modulo",
                "title_en": "Spacecraft module separation",
                "place_es": "la liberacion de un modulo desde una nave en maniobra",
                "place_en": "the release of a module from a maneuvering spacecraft",
                "decision_es": "decidir si basta el modelo aislado o si el empuje residual obliga a usar balance externo",
                "decision_en": "decide whether the isolated model is enough or whether residual thrust forces an external balance",
                "variable_es": "estimar cuanto pesa Jext frente al momento intercambiado entre las dos partes",
                "variable_en": "estimate how large Jext is compared with the momentum exchanged between the two parts",
                "limit_es": "hay que cambiar de modelo si los propulsores siguen activos o si la separacion dura demasiado",
                "limit_en": "the model must change if thrusters remain active or if the separation lasts too long",
            },
            {
                "title_es": "Auditoria de perturbaciones",
                "title_en": "Disturbance audit",
                "place_es": "una revision experimental para saber que fuerzas externas se estaban ignorando",
                "place_en": "an experimental review aimed at identifying which external forces were being ignored",
                "decision_es": "determinar si una discrepancia nace del sensor o de un mal supuesto de aislamiento",
                "decision_en": "determine whether a discrepancy comes from the sensor or from a poor isolation assumption",
                "variable_es": "usar DeltaPtot como prueba de fuego para detectar cuando el entorno si esta mandando",
                "variable_en": "use DeltaPtot as the decisive test for detecting when the environment is actually in control",
                "limit_es": "la lectura se vuelve ambigua si el intervalo temporal del analisis no coincide con el evento fisico",
                "limit_en": "the reading becomes ambiguous when the analysis time window does not match the physical event",
            },
            {
                "title_es": "Comparacion de fronteras del sistema",
                "title_en": "System-boundary comparison",
                "place_es": "un problema donde varias definiciones de sistema parecen razonables",
                "place_en": "a problem in which several system definitions seem reasonable",
                "decision_es": "elegir la frontera que convierte mas fuerzas en internas sin ocultar el mecanismo importante",
                "decision_en": "choose the boundary that turns more forces into internal ones without hiding the important mechanism",
                "variable_es": "seguir como cambian pTotI, pTotF y Jext cuando la frontera se mueve",
                "variable_en": "track how pTotI, pTotF, and Jext change when the boundary is moved",
                "limit_es": "no sirve redefinir el sistema si con ello desaparece la magnitud que se queria interpretar",
                "limit_en": "redefining the system is useless if the quantity that had to be interpreted disappears",
            },
        ],
    },
    "frontend/src/data_v2_i18n/fisica-clasica/mecanica/cantidad-de-movimiento/fundamentos/teorema-impulso-momento": {
        "concept_es": "teorema impulso-momento",
        "concept_en": "the impulse-momentum theorem",
        "scenarios": [
            {
                "title_es": "Plataforma de fuerza en golpe",
                "title_en": "Force-plate kick",
                "place_es": "una plataforma de fuerza que registra un golpe deportivo",
                "place_en": "a force plate that records a sports strike",
                "decision_es": "verificar si el impulso medido coincide con el cambio de momento reconstruido por video",
                "decision_en": "verify whether the measured impulse matches the momentum change reconstructed from video",
                "variable_es": "comparar J y DeltaP como dos lecturas del mismo balance y no como magnitudes independientes",
                "variable_en": "compare J and DeltaP as two readings of the same balance rather than independent quantities",
                "limit_es": "la comparacion falla si el video y la plataforma no usan el mismo sistema ni el mismo intervalo dt",
                "limit_en": "the comparison fails if the video and the plate do not use the same system or the same dt interval",
            },
            {
                "title_es": "Pulso de desaceleracion vehicular",
                "title_en": "Vehicle deceleration pulse",
                "place_es": "el analisis de una desaceleracion breve en seguridad vial",
                "place_en": "the analysis of a short deceleration pulse in road safety",
                "decision_es": "decidir si el pulso medido es compatible con la variacion real de momento del ocupante",
                "decision_en": "decide whether the measured pulse is compatible with the occupant's real momentum change",
                "variable_es": "mirar como Fmed depende de dt cuando el salto entre pi y pf ya esta fijado",
                "variable_en": "look at how Fmed depends on dt once the jump from pi to pf is already fixed",
                "limit_es": "hay que abandonar el leaf cuando aparecen varias fases de contacto mal separadas o rotaciones importantes",
                "limit_en": "the leaf must be abandoned when several contact phases are poorly separated or strong rotations appear",
            },
            {
                "title_es": "Martillo instrumentado",
                "title_en": "Instrumented hammer strike",
                "place_es": "una herramienta con sensor que golpea una pieza durante milisegundos",
                "place_en": "a sensorized tool striking a piece for a few milliseconds",
                "decision_es": "comprobar si la lectura del sensor describe bien la accion neta transferida",
                "decision_en": "check whether the sensor reading correctly describes the transferred net action",
                "variable_es": "usar la equivalencia entre J y DeltaP para auditar la calibracion del equipo",
                "variable_en": "use the equivalence between J and DeltaP to audit equipment calibration",
                "limit_es": "la lectura se degrada si el martillo rebota varias veces o si se mezcla fuerza tangencial no modelada",
                "limit_en": "the reading degrades when the hammer rebounds several times or when unmodeled tangential force is mixed in",
            },
            {
                "title_es": "Servicio de tenis",
                "title_en": "Tennis serve analysis",
                "place_es": "la comparacion entre saques con distinta ventana efectiva de contacto",
                "place_en": "the comparison between serves with different effective contact windows",
                "decision_es": "distinguir si la mejora viene de un mayor cambio de momento o de una mejor distribucion temporal",
                "decision_en": "distinguish whether improvement comes from a larger momentum change or from a better temporal distribution",
                "variable_es": "separar el papel de pi y pf del papel de Fmed para no atribuirlo todo a la fuerza pico",
                "variable_en": "separate the role of pi and pf from the role of Fmed so that everything is not attributed to peak force",
                "limit_es": "el modelo corto deja de bastar si la raqueta rota mucho o si la pelota recibe spin dominante",
                "limit_en": "the short model stops being enough when the racket rotates strongly or the ball receives dominant spin",
            },
            {
                "title_es": "Pinza robotica con impacto",
                "title_en": "Robotic gripper impact",
                "place_es": "la programacion de una pinza que toma una pieza sin danarla",
                "place_en": "the programming of a gripper that must pick a part without damaging it",
                "decision_es": "elegir si conviene reducir velocidad de entrada o alargar el tiempo de cierre",
                "decision_en": "choose whether it is better to reduce entry speed or lengthen the closing time",
                "variable_es": "comparar como cambia Fmed cuando el mismo DeltaP se consigue con estrategias temporales distintas",
                "variable_en": "compare how Fmed changes when the same DeltaP is achieved with different timing strategies",
                "limit_es": "hay que cambiar de modelo si la pieza se deforma mucho o si el control introduce varias fases de contacto",
                "limit_en": "the model must change when the part deforms strongly or the controller introduces several contact phases",
            },
        ],
    },
}

ANGULAR_CONFIGS = {
    "frontend/src/data_v2_i18n/fisica-clasica/mecanica/cantidad-de-movimiento/momento-angular/definicion-momento-angular": {
        "concept_es": "la definicion de momento angular",
        "concept_en": "the definition of angular momentum",
        "scenarios": [
            {
                "title_es": "Puerta empujada en distintos puntos",
                "title_en": "Door pushed at different points",
                "place_es": "una comparacion entre empujes aplicados cerca y lejos de la bisagra",
                "place_en": "a comparison between pushes applied near and far from the hinge",
                "decision_es": "decidir que accion produce mas efecto de giro aunque la fuerza lineal sea parecida",
                "decision_en": "decide which action produces more turning effect even when the linear force is similar",
                "variable_es": "el brazo perpendicular respecto al origen elegido y no solo el valor aislado de p",
                "variable_en": "the perpendicular lever arm with respect to the chosen origin rather than the isolated value of p alone",
                "limit_es": "la lectura simple deja de bastar si la puerta flexa, cambia el eje real o aparecen varios contactos simultaneos",
                "limit_en": "the simple reading stops being enough when the door flexes, the actual axis changes, or several contacts appear at once",
            },
            {
                "title_es": "Videoanalisis de una pelota y una porteria",
                "title_en": "Video analysis of a ball and a goal frame",
                "place_es": "una trayectoria que pasa cerca de un poste pero no lo alcanza",
                "place_en": "a trajectory that passes close to a goal post without hitting it",
                "decision_es": "elegir desde que origen conviene medir para interpretar si el movimiento tiene gran capacidad de giro",
                "decision_en": "choose which origin should be used to interpret whether the motion has a strong turning effect",
                "variable_es": "como cambia L cuando se mantiene p pero se modifica la distancia perpendicular al origen",
                "variable_en": "how L changes when p stays fixed but the perpendicular distance to the origin is modified",
                "limit_es": "hay que cambiar de modelo si la camara deforma la perspectiva o si el movimiento deja de ser aproximadamente plano",
                "limit_en": "the model must change if the camera distorts perspective or the motion stops being approximately planar",
            },
            {
                "title_es": "Rotor en banco didactico",
                "title_en": "Rotor on a teaching bench",
                "place_es": "un disco cuyo giro se mide con sensor de velocidad angular",
                "place_en": "a disk whose spin is measured with an angular-speed sensor",
                "decision_es": "traducir una lectura de omega a una lectura fisica de L sin perder el papel del momento de inercia",
                "decision_en": "translate a reading of omega into a physical reading of L without losing the role of moment of inertia",
                "variable_es": "la combinacion entre I y omega, porque una omega grande no implica por si sola un gran L",
                "variable_en": "the combination of I and omega, because a large omega does not by itself imply a large L",
                "limit_es": "la aproximacion falla si el eje oscila, si I cambia con la deformacion o si el sensor no separa spin y vibracion",
                "limit_en": "the approximation fails when the axis wobbles, I changes with deformation, or the sensor cannot separate spin from vibration",
            },
            {
                "title_es": "Comparacion entre corredor y martillo atletico",
                "title_en": "Comparison between a runner and a hammer throw",
                "place_es": "dos escenas con el mismo momento lineal pero geometria distinta",
                "place_en": "two scenes with the same linear momentum but different geometry",
                "decision_es": "explicar por que no basta conocer p para anticipar el efecto rotacional sobre un punto externo",
                "decision_en": "explain why knowing p is not enough to predict the rotational effect about an external point",
                "variable_es": "la orientacion entre r y p, porque el seno del angulo decide que fraccion del movimiento contribuye a L",
                "variable_en": "the orientation between r and p, because the sine of the angle decides which fraction of motion contributes to L",
                "limit_es": "no debe extrapolarse si el sistema real cambia de plano o si el origen relevante se mueve durante el proceso",
                "limit_en": "it should not be extrapolated when the real system changes plane or the relevant origin moves during the process",
            },
            {
                "title_es": "Auditoria de un origen mal elegido",
                "title_en": "Audit of a poorly chosen origin",
                "place_es": "una revision de informe donde dos calculos de L discrepan",
                "place_en": "a report review in which two calculations of L disagree",
                "decision_es": "determinar si el error viene del algebra o de haber cambiado el punto de referencia sin decirlo",
                "decision_en": "determine whether the error comes from algebra or from changing the reference point without stating it",
                "variable_es": "la consistencia entre origen, signo vectorial y distancia perpendicular usada en la lectura",
                "variable_en": "the consistency between origin, vector sign, and perpendicular distance used in the reading",
                "limit_es": "la auditoria deja de ser concluyente si cada calculo usa un sistema distinto o si el problema mezcla rotacion y traslacion no declaradas",
                "limit_en": "the audit stops being conclusive if each calculation uses a different system or if the problem mixes undeclared rotation and translation",
            },
        ],
    },
    "frontend/src/data_v2_i18n/fisica-clasica/mecanica/cantidad-de-movimiento/momento-angular/conservacion-momento-angular": {
        "concept_es": "la conservacion del momento angular",
        "concept_en": "the conservation of angular momentum",
        "scenarios": [
            {
                "title_es": "Taburete giratorio con pesas",
                "title_en": "Rotating stool with weights",
                "place_es": "una practica donde una persona recoge o separa masas mientras gira",
                "place_en": "a lab activity in which a person pulls masses inward or moves them outward while rotating",
                "decision_es": "decidir si el aumento de velocidad angular puede explicarse sin torque externo apreciable",
                "decision_en": "decide whether the increase in angular speed can be explained without appreciable external torque",
                "variable_es": "la comparacion entre Ii, If, omegai y omegaf antes de invocar una fuerza misteriosa",
                "variable_en": "the comparison among Ii, If, omegai, and omegaf before invoking a mysterious force",
                "limit_es": "la conservacion deja de ser fiable si aparece rozamiento fuerte en el eje o si alguien impulsa el sistema durante el cambio",
                "limit_en": "conservation stops being reliable when strong axle friction appears or someone pushes the system during the change",
            },
            {
                "title_es": "Patinadora analizada cuadro a cuadro",
                "title_en": "Skater analyzed frame by frame",
                "place_es": "un video donde la patinadora cambia de postura durante el giro",
                "place_en": "a video in which a skater changes posture while spinning",
                "decision_es": "comprobar si la lectura de Li y Lf sigue siendo coherente a pesar de ruido experimental",
                "decision_en": "check whether the reading of Li and Lf remains coherent despite experimental noise",
                "variable_es": "el torque externo acumulado durante DeltaT y no solo la variacion visible de omegaf",
                "variable_en": "the external torque accumulated over DeltaT rather than the visible change in omegaf alone",
                "limit_es": "hay que abandonar la lectura ideal si el apoyo transmite par apreciable o si el eje corporal se descentra mucho",
                "limit_en": "the ideal reading must be abandoned when the support transmits appreciable torque or the body axis shifts too much",
            },
            {
                "title_es": "Apertura de panel solar en satelite",
                "title_en": "Satellite solar-panel deployment",
                "place_es": "una maniobra espacial donde piezas internas se mueven sin apoyo externo cercano",
                "place_en": "a space maneuver in which internal parts move without nearby external support",
                "decision_es": "anticipar como cambia la velocidad angular del cuerpo principal al redistribuir masa",
                "decision_en": "predict how the main body's angular speed changes when mass is redistributed",
                "variable_es": "si el balance total Lf = Li se mantiene mientras cambia If y se reordena la masa",
                "variable_en": "whether the total balance Lf = Li remains valid while If changes and mass is rearranged",
                "limit_es": "el modelo se rompe si los propulsores corrigen la actitud durante la maniobra o si el despliegue dura demasiado",
                "limit_en": "the model breaks down when thrusters correct attitude during the maneuver or the deployment lasts too long",
            },
            {
                "title_es": "Colision giratoria en mesa de aire",
                "title_en": "Rotational collision on an air table",
                "place_es": "un choque oblicuo alrededor de un punto de referencia fijo",
                "place_en": "an oblique collision about a fixed reference point",
                "decision_es": "elegir si la conservacion angular aporta una ecuacion util ademas del balance lineal",
                "decision_en": "choose whether angular conservation adds a useful equation besides the linear balance",
                "variable_es": "el momento angular antes y despues del impacto respecto al mismo origen, no respecto a origenes cambiantes",
                "variable_en": "angular momentum before and after impact with respect to the same origin, not changing origins",
                "limit_es": "la herramienta pierde valor si el choque recibe un par externo del soporte o si el origen no permanece fijo",
                "limit_en": "the tool loses value when the collision receives an external torque from the support or the origin does not remain fixed",
            },
            {
                "title_es": "Auditoria de ruptura de conservacion",
                "title_en": "Audit of conservation breakdown",
                "place_es": "una discrepancia experimental donde omegaf no cuadra con el cambio de inercia esperado",
                "place_en": "an experimental discrepancy in which omegaf does not match the expected inertia change",
                "decision_es": "determinar si el fallo viene de datos malos o de un tau externo que no se habia modelado",
                "decision_en": "determine whether the mismatch comes from bad data or from an external tau that had not been modeled",
                "variable_es": "la estimacion de DeltaL = tau*DeltaT para saber si el entorno si tuvo capacidad de alterar L total",
                "variable_en": "the estimate of DeltaL = tau*DeltaT to decide whether the surroundings could actually alter total L",
                "limit_es": "la auditoria no cierra si el intervalo DeltaT esta mal elegido o si varias fuentes de torque se mezclan sin separarlas",
                "limit_en": "the audit cannot close if the interval DeltaT is poorly chosen or several torque sources are mixed without separation",
            },
        ],
    },
    "frontend/src/data_v2_i18n/fisica-clasica/mecanica/cantidad-de-movimiento/momento-angular/precesion": {
        "concept_es": "la precesion giroscopica",
        "concept_en": "gyroscopic precession",
        "scenarios": [
            {
                "title_es": "Rueda de bicicleta suspendida",
                "title_en": "Suspended bicycle wheel",
                "place_es": "una rueda sostenida por un extremo del eje en el laboratorio",
                "place_en": "a wheel held by one end of the axle in the laboratory",
                "decision_es": "estimar si el eje precesara lentamente o caera rapido cuando la rueda pierda giro",
                "decision_en": "estimate whether the axis will precess slowly or fall quickly as the wheel loses spin",
                "variable_es": "la razon entre el torque gravitatorio y el gran momento angular de spin",
                "variable_en": "the ratio between gravitational torque and the large spin angular momentum",
                "limit_es": "la formula simple deja de servir si hay nutacion grande, friccion fuerte o el eje cambia mucho de inclinacion",
                "limit_en": "the simple formula stops working when large nutation, strong friction, or large inclination changes appear",
            },
            {
                "title_es": "Trompo que se frena",
                "title_en": "Spinning top that is slowing down",
                "place_es": "la observacion de un trompo durante varios segundos de perdida de velocidad",
                "place_en": "the observation of a top during several seconds of spin decay",
                "decision_es": "decidir en que momento deja de ser defendible la aproximacion de precesion casi uniforme",
                "decision_en": "decide when the nearly uniform-precession approximation stops being defensible",
                "variable_es": "como aumenta Omegap cuando disminuye L aunque el torque externo casi no cambie",
                "variable_en": "how Omegap increases when L decreases even though the external torque barely changes",
                "limit_es": "hay que cambiar de modelo cuando la nutacion domina o cuando el contacto en la punta ya no es estable",
                "limit_en": "the model must change when nutation dominates or when contact at the tip is no longer stable",
            },
            {
                "title_es": "Diseno de sensor inercial elemental",
                "title_en": "Elementary inertial-sensor design",
                "place_es": "una discusion tecnica sobre cuanto giro principal hace falta para estabilizar un eje",
                "place_en": "a technical discussion about how much main spin is needed to stabilize an axis",
                "decision_es": "invertir la relacion para calcular que torque admisible corresponde a una precesion maxima",
                "decision_en": "invert the relation to compute which admissible torque corresponds to a maximum precession",
                "variable_es": "el despeje inverso que conecta Omegap con el tau tolerable para un L dado",
                "variable_en": "the inverse isolation that connects Omegap with the tolerable tau for a given L",
                "limit_es": "no basta con este leaf si hay pares variables, control activo o distribuciones de masa no bien conocidas",
                "limit_en": "this leaf is not enough when torques vary, active control appears, or mass distributions are poorly known",
            },
            {
                "title_es": "Precesion terrestre explicada con escala",
                "title_en": "Earth's precession explained by scale",
                "place_es": "una comparacion entre laboratorio y astronomia",
                "place_en": "a comparison between laboratory and astronomy",
                "decision_es": "mostrar por que un torque pequeno puede producir una precesion visible solo en tiempos enormes",
                "decision_en": "show why a small torque can produce visible precession only over enormous times",
                "variable_es": "el periodo Tp, que traduce una Omegap minuscula a una escala temporal interpretable",
                "variable_en": "the period Tp, which translates a tiny Omegap into an interpretable time scale",
                "limit_es": "la analogia se vuelve pobre si se olvidan las diferencias de rigidez, simetria y distribucion real de masa",
                "limit_en": "the analogy becomes poor when differences in rigidity, symmetry, and real mass distribution are ignored",
            },
            {
                "title_es": "Revision de datos de video y torque",
                "title_en": "Review of video and torque data",
                "place_es": "una medicion donde se combinan seguimiento del eje y estimacion de peso y brazo",
                "place_en": "a measurement combining axis tracking with weight-and-lever-arm estimation",
                "decision_es": "comprobar si la Omegap observada es compatible con M, d, I y omega medidos por separado",
                "decision_en": "check whether the observed Omegap is compatible with M, d, I, and omega measured separately",
                "variable_es": "la coherencia entre tau_g, L y el periodo Tp reconstruido desde las imagenes",
                "variable_en": "the coherence among tau_g, L, and the period Tp reconstructed from the images",
                "limit_es": "la comparacion falla si el origen del torque cambia, si el video pierde escala o si el eje no mantiene casi constante su angulo",
                "limit_en": "the comparison fails if the torque origin changes, video scaling is lost, or the axis does not keep an almost constant angle",
            },
        ],
    },
}

MASS_VARIABLE_CONFIGS = {
    "frontend/src/data_v2_i18n/fisica-clasica/mecanica/cantidad-de-movimiento/sistemas-de-masa-variable/balance-de-momento-con-flujo-de-masa": {
        "concept_es": "el balance de momento con flujo de masa",
        "concept_en": "momentum balance with mass flow",
        "scenarios": [
            {
                "title_es": "Cinta transportadora que recibe arena",
                "title_en": "Conveyor belt receiving sand",
                "place_es": "una cinta horizontal alimentada desde una tolva",
                "place_en": "a horizontal conveyor fed by a hopper",
                "decision_es": "calcular que fuerza externa hace falta para mantener velocidad constante mientras entra masa",
                "decision_en": "compute which external force is required to keep constant speed while mass enters",
                "variable_es": "el termino u*mdot frente a Fext, porque el frenado nace del momento que la arena debe ganar al entrar",
                "variable_en": "the u*mdot term versus Fext, because the braking comes from the momentum that the sand must gain when it enters",
                "limit_es": "el modelo deja de bastar si la arena rebota, se amontona o aparece rozamiento interno dominante",
                "limit_en": "the model stops being enough when the sand rebounds, piles up, or strong internal friction appears",
            },
            {
                "title_es": "Manguera de bomberos y retroceso",
                "title_en": "Fire hose recoil",
                "place_es": "el manejo de una manguera que expulsa agua a gran caudal",
                "place_en": "the handling of a hose ejecting water at high flow rate",
                "decision_es": "estimar si el operario puede compensar el retroceso o si hace falta apoyo mecanico",
                "decision_en": "estimate whether the operator can compensate the recoil or whether mechanical support is needed",
                "variable_es": "la rapidez con la que el flujo exporta momento y no solo la masa total de agua movida",
                "variable_en": "how fast the flow exports momentum rather than the total water mass alone",
                "limit_es": "la lectura se degrada si el chorro cambia de direccion, pulsa en el tiempo o el conducto flexa mucho",
                "limit_en": "the reading degrades when the jet changes direction, pulses in time, or the hose flexes strongly",
            },
            {
                "title_es": "Vagon con fuga vertical",
                "title_en": "Cart with vertical leak",
                "place_es": "un carro que pierde liquido por un orificio en el fondo",
                "place_en": "a cart losing liquid through a hole in the bottom",
                "decision_es": "decidir si la velocidad horizontal cambiara realmente o si solo cambia la masa transportada",
                "decision_en": "decide whether the horizontal speed will really change or whether only the carried mass changes",
                "variable_es": "la componente horizontal de u, porque sin ella el flujo no extrae momento en esa direccion",
                "variable_en": "the horizontal component of u, because without it the flow does not remove momentum in that direction",
                "limit_es": "hay que cambiar de modelo si el liquido sale inclinado, si hay rozamiento apreciable o si el carro rota",
                "limit_en": "the model must change when the liquid leaves at an angle, appreciable friction appears, or the cart rotates",
            },
            {
                "title_es": "Tolva dosificadora instrumentada",
                "title_en": "Instrumented feeder hopper",
                "place_es": "una linea industrial con sensores de caudal y fuerza",
                "place_en": "an industrial line with flow-rate and force sensors",
                "decision_es": "comprobar si las lecturas de fuerza cierran con el flujo de masa medido antes de ajustar el control",
                "decision_en": "check whether the force readings close with the measured mass flow before tuning the controller",
                "variable_es": "la coherencia entre dPdt, Fext y u*mdot en una misma ventana temporal",
                "variable_en": "the coherence among dPdt, Fext, and u*mdot over the same time window",
                "limit_es": "la auditoria falla si sensores y video no miran el mismo tramo o si el volumen de control se mueve",
                "limit_en": "the audit fails if sensors and video do not observe the same interval or if the control volume moves",
            },
            {
                "title_es": "Aspersor con dos salidas",
                "title_en": "Sprinkler with two outlets",
                "place_es": "un dispositivo que recibe agua y la expulsa por ramas simetricas",
                "place_en": "a device that receives water and expels it through symmetric branches",
                "decision_es": "elegir si puede suponerse cancelacion de momento o si una asimetria obliga a modelar fuerza neta",
                "decision_en": "choose whether momentum cancellation can be assumed or whether an asymmetry forces a net-force model",
                "variable_es": "la suma vectorial de los flujos de salida y no cada chorro aislado",
                "variable_en": "the vector sum of the outlet flows rather than each jet in isolation",
                "limit_es": "la simplificacion se rompe si las ramas no son equivalentes o si el flujo cambia de regimen",
                "limit_en": "the simplification breaks when the branches are not equivalent or the flow changes regime",
            },
        ],
    },
    "frontend/src/data_v2_i18n/fisica-clasica/mecanica/cantidad-de-movimiento/sistemas-de-masa-variable/ecuacion-del-cohete": {
        "concept_es": "la ecuacion del cohete",
        "concept_en": "the rocket equation",
        "scenarios": [
            {
                "title_es": "Maniobra orbital de satelite pequeno",
                "title_en": "Small-satellite orbital maneuver",
                "place_es": "un satelite que debe elevar ligeramente su orbita con combustible limitado",
                "place_en": "a satellite that must raise its orbit slightly with limited propellant",
                "decision_es": "comprobar si el DeltaV pedido cabe en la razon de masas disponible sin comprometer masa final",
                "decision_en": "check whether the requested DeltaV fits within the available mass ratio without compromising final mass",
                "variable_es": "la relacion entre DeltaV, ve y m0/mf, porque el combustible disponible entra solo a traves del logaritmo",
                "variable_en": "the relation among DeltaV, ve, and m0/mf, because available propellant enters only through the logarithm",
                "limit_es": "la lectura ideal deja de bastar si el encendido es largo, la gravedad pesa o el empuje no puede tomarse cuasi instantaneo",
                "limit_en": "the ideal reading stops being enough when the burn is long, gravity matters, or thrust cannot be treated as quasi-instantaneous",
            },
            {
                "title_es": "Cohete de agua escolar",
                "title_en": "School water rocket",
                "place_es": "un lanzamiento corto donde se comparan presiones y masa de agua",
                "place_en": "a short launch in which pressure and water mass are compared",
                "decision_es": "elegir si conviene cargar mas agua o aligerar la estructura para ganar altura util",
                "decision_en": "choose whether to load more water or lighten the structure to gain useful height",
                "variable_es": "la masa final mf, porque demasiada agua mejora el empuje inicial pero empeora la razon de masas global",
                "variable_en": "the final mass mf, because too much water improves initial thrust but worsens the global mass ratio",
                "limit_es": "la ecuacion simple se vuelve pobre si la resistencia del aire y la expansion del agua dominan toda la maniobra",
                "limit_en": "the simple equation becomes poor when air drag and water expansion dominate the whole maneuver",
            },
            {
                "title_es": "Predimensionado de etapa superior",
                "title_en": "Upper-stage preliminary sizing",
                "place_es": "una discusion de ingenieria sobre cuanto propelente debe cargar una etapa final",
                "place_en": "an engineering discussion about how much propellant an upper stage should carry",
                "decision_es": "reconstruir m0 o mf a partir de un DeltaV objetivo antes de fijar tanques y carga util",
                "decision_en": "reconstruct m0 or mf from a target DeltaV before fixing tanks and payload",
                "variable_es": "los despejes m0_from_dv y dv_solve_mf, porque convierten la ecuacion en una herramienta de diseno",
                "variable_en": "the m0_from_dv and dv_solve_mf rearrangements, because they turn the equation into a design tool",
                "limit_es": "hay que ampliar el modelo si el motor cambia mucho de ve o si la estructura no puede considerarse masa inerte fija",
                "limit_en": "the model must be expanded when the engine changes ve strongly or the structure cannot be treated as fixed inert mass",
            },
            {
                "title_es": "Comparacion entre motores quimico e ionico",
                "title_en": "Chemical versus ion-engine comparison",
                "place_es": "una seleccion de propulsion para una mision de largo alcance",
                "place_en": "a propulsion trade study for a long-range mission",
                "decision_es": "estimar si compensa subir ve aunque el empuje instantaneo sea menor",
                "decision_en": "estimate whether increasing ve is worth it even when instantaneous thrust is lower",
                "variable_es": "ve, porque una mejora en velocidad de eyeccion reduce de forma directa la razon de masas requerida",
                "variable_en": "ve, because an improvement in exhaust speed directly reduces the required mass ratio",
                "limit_es": "el leaf no decide por si solo si el motor sirve, porque tambien importan potencia disponible y tiempo de maniobra",
                "limit_en": "the leaf alone cannot decide whether the engine is suitable, because available power and maneuver time also matter",
            },
            {
                "title_es": "Auditoria de presupuesto de DeltaV",
                "title_en": "DeltaV budget audit",
                "place_es": "una revision de mision donde el presupuesto de maniobras ya no cuadra",
                "place_en": "a mission review in which the maneuver budget no longer closes",
                "decision_es": "detectar si el fallo viene de una estimacion mala de mf, de ve o del propio DeltaV requerido",
                "decision_en": "detect whether the mismatch comes from a bad estimate of mf, ve, or of the required DeltaV itself",
                "variable_es": "que despeje inverso explica mejor la discrepancia sin esconder el coste real de combustible",
                "variable_en": "which inverse rearrangement best explains the discrepancy without hiding the real propellant cost",
                "limit_es": "la auditoria ideal no basta si hubo perdidas gravitacionales, arrastre o etapas que no se modelaron por separado",
                "limit_en": "the ideal audit is not enough when gravitational losses, drag, or stages were not modeled separately",
            },
        ],
    },
}


if __name__ == "__main__":
    write_leafs({**FUNDAMENTOS_CONFIGS, **ANGULAR_CONFIGS, **MASS_VARIABLE_CONFIGS})
