#!/usr/bin/env python3
import pathlib

leaf_dir = pathlib.Path("frontend/src/data_v2_i18n/fisica-clasica/mecanica/mecanica-analitica/lagrangiano/simetrias-y-conservaciones")

# ejemplos.en.md
ejemplos_en = """# Examples: Symmetries and Conserved Quantities

## Example 1: Cyclic Coordinate

A particle in a central potential where the Lagrangian does not depend on angle $\\theta$. The coordinate $\\theta$ is cyclic (does not appear explicitly). Its conjugate momentum must satisfy:

{{f:momento_conjugado}}

Therefore angular momentum is conserved, reducing the problem dimension.

## Example 2: Time-Independent Lagrangian

A mass-spring system where the Lagrangian has no explicit time dependence. Total energy is:

{{f:energia_mecanica_lagrangiano}}

which is conserved throughout the motion.

## Example 3: Approximate Symmetry Violation

A damped oscillator where dissipation slowly breaks energy conservation. The Noether charge [[Q]] is no longer exactly conserved but decays over time.
"""

# modelos.en.md
modelos_en = """# Models and Conceptual Framework

## Lagrangian Symmetry Model

The fundamental principle: when the Lagrangian [[L]] is invariant under a continuous transformation (parameterized by infinitesimal parameter), a conserved quantity [[Q]] is generated by Noether's theorem:

{{f:carga_noether}}

where [[p_i]] are canonical momenta [[conjugate to coordinates q_i]].

## Cyclic Coordinates

A coordinate is cyclic if it does not appear in the Lagrangian. Its conjugate momentum is automatically conserved. This property simplifies multidimensional problems.

## Exact versus Approximate Symmetries

Exact symmetries hold under all conditions. Approximate symmetries hold only under stated assumptions (ignoring certain terms or forces). The rate of change of a conserved quantity under approximate symmetry can be quantified.
"""

# errores.en.md
errores_en = """# Common Errors and Misconceptions

## Error 1: Confusing "Nearly Constant" with "Conserved"

A quantity that changes slowly is not necessarily exactly conserved. Always estimate its rate of change explicitly. If the rate is negligible over your time scale, treat it as approximately conserved; otherwise, account for the drift.

## Error 2: Not Verifying Invariance

Do not assume a quantity is conserved just because it has the right form. Always verify that the Lagrangian is actually invariant (unchanged under the proposed transformation) before claiming conservation.

## Error 3: Assuming Global Symmetry When Only Local

A symmetry that holds only in a restricted region of phase space is not a true global symmetry. Check that symmetry transformations are well-defined everywhere in your domain.

## Error 4: Mixing Dynamical and Topological Conserved Quantities

Conserved quantities from Noether (dynamical) differ in origin and violation mechanisms from topological charges. Do not treat them identically.
"""

# aplicaciones.en.md
aplicaciones_en = """# Applications and Real-World Context

## Celestial Mechanics

Planetary orbits conserve energy and angular momentum due to Lagrangian symmetries (time-translation and rotational invariance). These two integrals alone predict orbital elements without solving equations point-by-point.

## Molecular Dynamics

If intermolecular potentials depend only on relative distances, translation and rotation invariance reduce computational burden by separating center-of-mass (trivial) from internal (interesting) dynamics.

## Gauge Field Theory

Electromagnetic theory conservation of charge emerges from gauge symmetry of the Lagrangian. This connection unifies charge conservation with local symmetry principles.

## Engineering Control

Exploiting known conserved quantities in system design allows building controllers that preserve invariants, simplifying stability analysis.
"""

# historia.en.md
historia_en = """# Historical Context

## Emmy Noether's Theorem (1915)

Emmy Noether proved that symmetries of the action generate conservation laws. This unified seemingly disparate principles (energy, momentum, angular momentum conservation) under one framework.

## Impact on Physics

Noether's result became the foundation for modern theoretical physics. The Standard Model is built on the principle that all interactions arise from symmetries and their associated conserved charges.

## Mathematical Foundations

The theorem rests on the principle of least action and variations. Symmetries of the action naturally yield conservation laws through the structure of equations of motion.
"""

files_to_write = {
    "ejemplos.en.md": ejemplos_en,
    "modelos.en.md": modelos_en,
    "errores.en.md": errores_en,
    "aplicaciones.en.md": aplicaciones_en,
    "historia.en.md": historia_en,
}

for filename, content in files_to_write.items():
    filepath = leaf_dir / filename
    filepath.write_text(content, encoding="utf-8")
    print(f"Updated {filename}")

print("All .en.md files updated successfully.")
