export const SI_PREFIXES = [
  { id: "", label: "—", symbol: "", factor: 1 },

  // Submúltiplos
  { id: "q",  label: "quecto", symbol: "q", factor: 1e-30 },
  { id: "r",  label: "ronto",  symbol: "r", factor: 1e-27 },
  { id: "y",  label: "yocto",  symbol: "y", factor: 1e-24 },
  { id: "z",  label: "zepto",  symbol: "z", factor: 1e-21 },
  { id: "a",  label: "atto",   symbol: "a", factor: 1e-18 },
  { id: "f",  label: "femto",  symbol: "f", factor: 1e-15 },
  { id: "p",  label: "pico",   symbol: "p", factor: 1e-12 },
  { id: "n",  label: "nano",   symbol: "n", factor: 1e-9 },
  { id: "µ",  label: "micro",  symbol: "µ", factor: 1e-6 },
  { id: "m",  label: "mili",   symbol: "m", factor: 1e-3 },
  { id: "c",  label: "centi",  symbol: "c", factor: 1e-2 },
  { id: "d",  label: "deci",   symbol: "d", factor: 1e-1 },
  { id: "da", label: "deca",   symbol: "da", factor: 1e1 },
  { id: "h",  label: "hecto",  symbol: "h",  factor: 1e2 },
  { id: "k",  label: "kilo",   symbol: "k", factor: 1e3 },
  { id: "M",  label: "mega",   symbol: "M", factor: 1e6 },
  { id: "G",  label: "giga",   symbol: "G", factor: 1e9 },
  { id: "T",  label: "tera",   symbol: "T", factor: 1e12 },
  { id: "P",  label: "peta",   symbol: "P", factor: 1e15 },
  { id: "E",  label: "exa",    symbol: "E", factor: 1e18 },
  { id: "Z",  label: "zetta",  symbol: "Z", factor: 1e21 },
  { id: "Y",  label: "yotta",  symbol: "Y", factor: 1e24 },
  { id: "R",  label: "ronna",  symbol: "R", factor: 1e27 },
  { id: "Q",  label: "quetta", symbol: "Q", factor: 1e30 },
];
