id: fenomenos-criticos
titulo: fenomenos-criticos
type: leaf
orden: 276300
niveles:
  - ESO
  - BACHILLERATO
  - UNIVERSIDAD
  - EXTRACURRICULAR
icon: 🪢
ruta_relativa: fisica-clasica/termodinamica-estadistica/transiciones-de-fase/fenomenos-criticos
descripcion: 'Subtema: Fenomenos Criticos. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
