id: relatividad-general-intro
titulo: relatividad-general-intro
type: leaf
orden: 315000
niveles:
  - EXTRACURRICULAR
icon: 🔊
ruta_relativa: fisica-moderna/relatividad/relatividad-general-intro
descripcion: 'Subtema: Relatividad General Intro. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
