id: materia-oscura-energia-oscura
titulo: materia-oscura-energia-oscura
type: leaf
orden: 453000
niveles:
  - EXTRACURRICULAR
icon: ☢️
ruta_relativa: fisica-avanzada/cosmologia/materia-oscura-energia-oscura
descripcion: 'Subtema: Materia Oscura Energia Oscura. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
