version: 1
id: efecto-venturi
nombre: Efecto Venturi
titulo: efecto-venturi
type: leaf
area: fisica-clasica
bloque: mecanica
subbloque: fluidos
orden: 218331
niveles:
  - ESO
  - BACHILLERATO
  - UNIVERSIDAD
icon: 💧
ruta_relativa: fisica-clasica/mecanica/fluidos/dinamica-de-fluidos/aplicaciones-de-bernoulli/efecto-venturi
descripcion: Aceleracion del flujo por estrechamiento.
descripcion_corta: Aceleracion del flujo por estrechamiento.
dificultad: 2
tiempo_estimado_min: 55
prerequisitos:
  - fisica-clasica/mecanica/fluidos/dinamica-de-fluidos/ecuacion-de-bernoulli
tags:
  - fluidos
  - aplicaciones-de-bernoulli
  - efecto-venturi
graficos:
  - Coord
  - Svg
