id: regulacion-primaria-secundaria-terciaria
titulo: regulacion-primaria-secundaria-terciaria
type: leaf
orden: 593500
niveles:
  - EXTRACURRICULAR
icon: ⭐
ruta_relativa: sostenibilidad-energia/transporte-de-la-energia/estabilidad-de-la-red/regulacion-primaria-secundaria-terciaria
descripcion: 'Subtema: Regulacion Primaria Secundaria Terciaria. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
