id: difraccion-de-la-luz
titulo: difraccion-de-la-luz
type: leaf
orden: 297220
niveles:
  - ESO
  - BACHILLERATO
  - UNIVERSIDAD
  - EXTRACURRICULAR
icon: 🪟
ruta_relativa: fisica-clasica/electromagnetismo/optica/optica-fisica/difraccion-de-la-luz
descripcion: 'Subtema: Difraccion de la Luz. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
