id: inductiva
titulo: inductiva
type: leaf
orden: 294220
niveles:
  - UNIVERSIDAD
icon: ☢️
ruta_relativa: fisica-clasica/electromagnetismo/corriente-alterna/reactancia/inductiva
descripcion: 'Subtema: Inductiva. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
