id: red-electrica
titulo: red-electrica
type: leaf
orden: 298100
niveles:
  - ESO
  - BACHILLERATO
  - UNIVERSIDAD
  - EXTRACURRICULAR
icon: 🧷
ruta_relativa: fisica-clasica/electromagnetismo/electricidad-domestica/red-electrica
descripcion: 'Subtema: Red Electrica. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
