id: brayton-rankine
titulo: brayton-rankine
type: leaf
orden: 258140
niveles:
  - BACHILLERATO
  - UNIVERSIDAD
  - EXTRACURRICULAR
icon: 🎛️
ruta_relativa: fisica-clasica/termodinamica/maquinas-termicas/ciclos-termodinamicos/brayton-rankine
descripcion: 'Subtema: Brayton Rankine. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
