id: reflexion
titulo: reflexion
type: leaf
orden: 297110
niveles:
  - ESO
  - BACHILLERATO
  - UNIVERSIDAD
  - EXTRACURRICULAR
icon: ⏲️
ruta_relativa: fisica-clasica/electromagnetismo/optica/optica-geometrica/reflexion
descripcion: 'Subtema: Reflexion. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
