id: interacciones-fundamentales
titulo: interacciones-fundamentales
type: leaf
orden: 432000
niveles:
  - EXTRACURRICULAR
icon: 🚇
ruta_relativa: fisica-avanzada/fisica-particulas/interacciones-fundamentales
descripcion: 'Subtema: Interacciones Fundamentales. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
