id: inercia-del-sistema-electrico
titulo: inercia-del-sistema-electrico
type: leaf
orden: 593300
niveles:
  - EXTRACURRICULAR
icon: 🔅
ruta_relativa: sostenibilidad-energia/transporte-de-la-energia/estabilidad-de-la-red/inercia-del-sistema-electrico
descripcion: 'Subtema: Inercia del Sistema Electrico. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
