id: inductancia-mutua
titulo: inductancia-mutua
type: leaf
orden: 2100420
niveles:
  - UNIVERSIDAD
icon: 🧯
ruta_relativa: fisica-clasica/electromagnetismo/induccion-electromagnetica/inductancia/inductancia-mutua
descripcion: 'Subtema: Inductancia Mutua. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
