"""
utils
Utilidades básicas: IO, YAML, conteo, normalización de texto

LECTURA IA: Este módulo reexporta las funciones del validador relacionadas
con "utils". Para editar la lógica, busca la función en este listado
y edítala en _core.py en la línea indicada.
"""
from ._core import (
    CheckResult,
    _any_token_present,
    _build_formula_search_entry,
    _canonicalize_section_fragment,
    _collect_formula_entries,
    _collect_interpretation_target_keys,
    _collect_magnitude_entries,
    _collect_markdown_files,
    _core_formula_labels,
    _core_magnitude_labels,
    _count_shared_core_hits,
    _entry_present_in_text,
    _entry_tokens,
    _extract_interpretation_target_text,
    _extract_markdown_section,
    _extract_section_bodies,
    _first_long_sentence,
    _formula_is_important,
    _formula_ref_lines_outside_section,
    _iter_map_nodes,
    _markdown_words_without_formula_refs,
    _marker_hit,
    _normalize_compare_text,
    _normalize_compare_value,
    _normalize_text_for_search,
    _rank_core_formulas,
    _rank_core_magnitudes,
    _read_optional_text,
    _safe_dict,
    _safe_list,
    _safe_yaml_list,
    _section_similarity,
    _significant_words,
    _split_application_body_and_markers,
    _strip_inline_math_delimiters,
    _strip_markdown_protected_spans,
    _text_contains_token,
    _yaml_to_searchable_text,
    analyze_required_heading_structure,
    build_prose_quality_checks,
    check_required_emoji_prefixes,
    collect_markdown_word_counts,
    configure_console_encoding,
    count_words,
    extract_leaf_dir,
    extract_markdown_sections_by_level,
    extract_math_tokens,
    extract_numbered_h2_sections,
    find_bare_formula_issues,
    find_empty_example_part_issues,
    find_generic_markdown_template_issues,
    find_leaf_dirs,
    find_map_ancestor_chain_by_leaf_id,
    find_markdown_math_render_issues,
    find_missing_sections,
    find_mojibake_lines,
    find_placeholder_lines,
    find_repeated_long_sentences,
    find_theory_inline_highlight_formula_issues,
    find_theory_variety_issues,
    find_visible_formula_id_issues,
    find_workspace_root,
    gather_magnitude_symbols,
    heading_matches,
    is_leaf_dir,
    load_yaml,
    normalize_heading_title,
    normalize_prose_fragment,
    normalize_symbol,
    parse_markdown_headings,
    read_text,
    repair_mojibake,
    rough_english_check,
    strip_inline_math,
    strip_js_comments,
    validate_history,
)

# Re-exportar todo para que 'from .module import *' funcione
__all__ = ["CheckResult", "_any_token_present", "_build_formula_search_entry", "_canonicalize_section_fragment", "_collect_formula_entries", "_collect_interpretation_target_keys", "_collect_magnitude_entries", "_collect_markdown_files", "_core_formula_labels", "_core_magnitude_labels", "_count_shared_core_hits", "_entry_present_in_text", "_entry_tokens", "_extract_interpretation_target_text", "_extract_markdown_section", "_extract_section_bodies", "_first_long_sentence", "_formula_is_important", "_formula_ref_lines_outside_section", "_iter_map_nodes", "_markdown_words_without_formula_refs", "_marker_hit", "_normalize_compare_text", "_normalize_compare_value", "_normalize_text_for_search", "_rank_core_formulas", "_rank_core_magnitudes", "_read_optional_text", "_safe_dict", "_safe_list", "_safe_yaml_list", "_section_similarity", "_significant_words", "_split_application_body_and_markers", "_strip_inline_math_delimiters", "_strip_markdown_protected_spans", "_text_contains_token", "_yaml_to_searchable_text", "analyze_required_heading_structure", "build_prose_quality_checks", "check_required_emoji_prefixes", "collect_markdown_word_counts", "configure_console_encoding", "count_words", "extract_leaf_dir", "extract_markdown_sections_by_level", "extract_math_tokens", "extract_numbered_h2_sections", "find_bare_formula_issues", "find_empty_example_part_issues", "find_generic_markdown_template_issues", "find_leaf_dirs", "find_map_ancestor_chain_by_leaf_id", "find_markdown_math_render_issues", "find_missing_sections", "find_mojibake_lines", "find_placeholder_lines", "find_repeated_long_sentences", "find_theory_inline_highlight_formula_issues", "find_theory_variety_issues", "find_visible_formula_id_issues", "find_workspace_root", "gather_magnitude_symbols", "heading_matches", "is_leaf_dir", "load_yaml", "normalize_heading_title", "normalize_prose_fragment", "normalize_symbol", "parse_markdown_headings", "read_text", "repair_mojibake", "rough_english_check", "strip_inline_math", "strip_js_comments", "validate_history"]
