version: 1
id: sustentacion
nombre: Sustentacion
titulo: sustentacion
type: leaf
area: fisica-clasica
bloque: mecanica
subbloque: fluidos
orden: 218333
niveles:
  - ESO
  - BACHILLERATO
  - UNIVERSIDAD
icon: 💧
ruta_relativa: fisica-clasica/mecanica/fluidos/dinamica-de-fluidos/aplicaciones-de-bernoulli/sustentacion
descripcion: Generacion de sustentacion aerodinamica.
descripcion_corta: Generacion de sustentacion aerodinamica.
dificultad: 2
tiempo_estimado_min: 55
prerequisitos:
  - fisica-clasica/mecanica/fluidos/dinamica-de-fluidos/ecuacion-de-bernoulli
tags:
  - fluidos
  - aplicaciones-de-bernoulli
  - sustentacion
graficos:
  - Coord
  - Svg
  - Dcl
