id: tecnologia-digital
titulo: tecnologia-digital
type: leaf
orden: 5113000
niveles:
  - EXTRACURRICULAR
icon: 🌈
ruta_relativa: sostenibilidad-energia/energia-y-tecnologia/tecnologia-digital
descripcion: 'Subtema: Tecnologia Digital. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
