id: residuos
titulo: residuos
type: leaf
orden: 573300
niveles:
  - EXTRACURRICULAR
icon: 🛫
ruta_relativa: sostenibilidad-energia/fuentes-de-energia/energia-nuclear/residuos
descripcion: 'Subtema: Residuos. Teoría, fórmulas, ejemplos y aplicaciones.'
dificultad: ''
tiempo_estimado_min: null
prerequisitos: []
tags: []
